### ISSUE TITLE
"react/jsx-wrap-multilines": "never" option 

### ISSUE THREAD

**Issue by ghost** [jsx-eslint/eslint-plugin-react#1035]
Hi, it would be cool, to have that option available.

I am working currently in a team, where the members decided to use that explicit syntax:

```
return <div>
  <div />
</div>
```
I tried `no-extra-parens` but it did't worked for return statements. So I am here ;)

Would be nice to have the never option like: 

`"react/jsx-wrap-multilines": ["error", "never"]`

**Comment by ljharb** [comment]
Would "never" mean that you can't ever have multiline jsx?

**Comment by dropfen** [comment]
"never" would mean, never wrap jsx in parentheses.

**Comment by ljharb** [comment]
Gotcha, that makes sense and seems reasonable (although I personally find "never wrap" repulsive).

We'd need to change the schema so it accepted an optional string "always"|"never" before the object, and when the string was omitted (with or without the object), "always" was assumed.

**Comment by plonko** [comment]
Don't know if it's helpful but see (converse) discussion in Standard for more examples: https://github.com/standard/standard/issues/710

**Comment by craigcosmo** [comment]
What does the explicit syntax mean ?
