### ISSUE TITLE
react-in-jsx-scope satisfied by import from incorrect module name

### ISSUE THREAD

**Issue by EyalPerry** [jsx-eslint/eslint-plugin-react#1434]
Example below (note module name):

import React from "mobx-react"
..

Issue:
React is defined, but not imported from the correct module.
This actually fails at runtime, while satisfying the said eslint plugin.
If there is a way to make the plugin more strict and explicit about this- it would be fantastic.

**Comment by jseminck** [comment]
According to the code, even `const React = {};` satisfies the rule.

I suppose technically it's a bug, yes.

**Comment by ljharb** [comment]
The rule is really simple - all it does is look for the configured pragma in scope.

To be stricter, we'd have to allow the rule to be configured with "whether it's a global or required/imported", and if the latter, what the package name is. I'm not sure it's worth the complexity.
