### ISSUE TITLE
displayName in components should be static

### ISSUE THREAD

**Issue by rondonjon** [jsx-eslint/eslint-plugin-react#2581]
The `react/display-name` documentation doesn't explicitly state it, but the rule seems to accept display names as *properties* inside components.

=> Documentation needs to be updated

When the `displayName` was defined as a property, I think the rule should ensure that the declaration is `static`, so the following case should be rejected:

```
class Demo extends Component {
  displayName = "Demo"
}
```

Whereas the following should be accepted:

```
class Demo extends Component {
  static displayName = "Demo"
}
```

**Comment by ljharb** [comment]
We should definitely add test cases to ensure that a non-static class field does not satisfy the rule; additionally, we should probably add an option that forces it to be a static class field rather than an external property.

**Comment by ljharb** [comment]
In your example, however, the function’s name is sufficient, and your non-static class field has no effect. You’d need to use an anonymous class with a non-static property to see if the rule really accepted it (i believe it won’t)

**Comment by ljharb** [comment]
Either `static-property-placement` or `no-typos` should probably handle this.
