### ISSUE TITLE
Make jsx-no-script-url use shared settings to specify link components

### ISSUE THREAD

**Issue by burtek** [jsx-eslint/eslint-plugin-react#2865]
Why do we have to specify Link components in `react/jsx-no-script-url` settings when we already have that in shared config? Can't shared config be used here, as it is in `react/jsx-no-target-blank`?

**Comment by ljharb** [comment]
That's a very good point. This could possibly be a non-breaking change - to make the rule, in the absence of specific inline config, defer to the shared config. It'd be worth a PR.

**Comment by burtek** [comment]
I can try it this weekend if I find time
