### ISSUE TITLE
[feature request] react/jsx-newline

### ISSUE THREAD

**Issue by adrienharnay** [jsx-eslint/eslint-plugin-react#3033]
Hi,

I would find it interesting to provide a new option to the [react/jsx-newline](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-newline.md) rule, so that there is a newline between JSX expressions ONLY if they are multiline.

I find that single line JSX expressions are easier to read and don't require a space between them, but multiline expressions can quickly become hard to read.

Would anyone be eager to help me implement this feature, as this would be the first rule I would contributing to the project?

Thanks in advance!

**Comment by ljharb** [comment]
Can you give an example of a single-line component? I'm having trouble imagining when a component would be so simple that it's best expressed as a single line.

**Comment by adrienharnay** [comment]
I realise now an example would have helped, here it is:

```
const MyComponent = () => {
  return (
    <div>
      <OneLineComponent />
      <AnotherOneLineComponent prop={prop} />
      
      <MultilineComponent
        prop1={prop1}
        prop2={prop2}
      />

      <OneLineComponent />
    </div>
  );
}
```

I was more talking about JSX expressions than components, sorry again for the confusion.

**Comment by ljharb** [comment]
ahhh ok, thanks. That sounds like a great option to me.

**Comment by adrienharnay** [comment]
Would anyone be up to help me tackle this?

**Comment by ljharb** [comment]
I'm happy to review a PR, and give guidance if you have specific questions.

**Comment by ljharb** [comment]
@TildaDares go for it! I think we'd want to keep the same behavior by default, but add a new option that ignored single-line jsx expressions.
