### ISSUE TITLE
Use `const` when autofixing `react/function-component-definition`

### ISSUE THREAD

**Issue by doasync** [jsx-eslint/eslint-plugin-react#3152]
I want to use only arrow functions for named components: `[2, { "namedComponents": "arrow-function" }]`

ESlint autofixes function-declaration component...

```ts
function Component (props) {
  return <div />;
}
```

into arrow-function component using `var`

```ts
var Component = (props) => {
  return <div />;
};
```

Who uses `var` in 2021? I want to use `const` instead.

**Comment by ljharb** [comment]
Many people do. Either way, that’s why the prefer-const rule handles.

Rule autofixes are meant to work in concert with other rules, not in isolation.

**Comment by doasync** [comment]
@ljharb `prefer-const` doesn't autofix `var`

**Comment by ljharb** [comment]
That is a fair point.

I suppose that anyone using jsx can handle using `const`, so this would be a reasonable change to make here *if* the component is using jsx.
