### ISSUE TITLE
No Array or Object methods in render

### ISSUE THREAD

**Issue by shamilovtim** [jsx-eslint/eslint-plugin-react#3282]
Hello, I wanted to gauge appetite for implementation of a rule like this. 

Problem: In a large React project, it is difficult to keep Array/Object operations out of function component bodies. 

Solution: No Array or Object methods in render 

```typescript
const Screen () => {
   const { data: posts } = useFetchPosts();
   const filteredPosts = posts.filter((post) => post.isActive)); 
      // eslint-error: No array methods in render.
      // Please either memoize or move this operation inside a
      // useEffect, useState or side effect handler (like onClick)


   const onPress = () => console.log(filteredPosts);
   return <Child onPress={onPress} />
}
```
In this case, this error would be resolved by moving the operation into onPress.

Also: a condition to allow it from a useMemo or useCallback. I think It would need to error on immediately executed functions as well since that would result in the same problem.

**Comment by ljharb** [comment]
An array filter isn't expensive, though.

**Comment by shamilovtim** [comment]
> An array filter isn't expensive, though.

Right but this isn't a commentary on the expense of Array.filter? We use React Native and there's a level of interest in keeping Array/Object methods out of render where they can often clog the JS thread on Android devices during back to back renders.

**Comment by ljharb** [comment]
The claimed motivation for the rule is expense - the phrase you used was "expensive operations".

Array/Object operations on small (read: less than hundreds of thousands of items) arrays/objects should be virtually instantaneous. You certainly *can* use `useMemo` or `useCallback` on them, but you needn't, I suspect even on an Android device.

In this specific case, obviously the filter isn't needed until inside the onPress, so that's the proper place to do the operation, but that has nothing to do with the render path, or array/object methods.

I'm happy to consider a rule that helps rendering performance, to be clear - but a rule that broadly warns on common, trivial transformations of arrays and/or objects would cause a lot more harm than benefit.

**Comment by shamilovtim** [comment]
> The claimed motivation for the rule is expense - the phrase you used was "expensive operations".
> 
> Array/Object operations on small (read: less than hundreds of thousands of items) arrays/objects should be virtually instantaneous. You certainly _can_ use `useMemo` or `useCallback` on them, but you needn't, I suspect even on an Android device.
> 
> In this specific case, obviously the filter isn't needed until inside the onPress, so that's the proper place to do the operation, but that has nothing to do with the render path, or array/object methods.
> 
> I'm happy to consider a rule that helps rendering performance, to be clear - but a rule that broadly warns on common, trivial transformations of arrays and/or objects would cause a lot more harm than benefit.

Sorry, I'm not familiar with the nitty gritty of the JS engine. What about when an application is mounting hundreds of components and all of them have separate calls to the JS thread? My understanding is that JS is single threaded. How does one thread arbitrate hundreds of React components mounting all at once while many of them are calling synchronous collection iteration methods like `Array.sort()` in their function bodies? Mobile vitals are frozen frames or stalls, which seem to correlate with object and array iteration. As phones start to adapt 120hz refresh rates we're going to see more and more people trying to squeeze performance out by removing stuff like iteration from the render method.

I wish I could tag some more mainline React Native community members to get their perspectives. Off the top of my head maybe @mrousavy @satya164

**Comment by ljharb** [comment]
Yes, JS is single-threaded, as is the JS on the entire web, and in practice what you're describing just isn't a problem as far as I'm aware.

Again, it's perfectly fine to use hooks like useMemo or useCallback and to optimize stuff, especially when you've profiled and found actual performance issues. I'm not convinced, however, that it'd be beneficial to always do that - memoization has a cost, too.

**Comment by satya164** [comment]
I see I was mentioned here and I agree with @ljharb. I'd say that:

- Such methods will only make a noticeable difference in very large arrays, it makes sense to memoize in those cases. But it's rather a case-by-case basis and a general rule like this won't work. Personally, I have never encountered array iterations to be a performance issue in my profiling. Memoization has its own overhead.
- Moving such operations to `useEffect` etc. makes it more manual work to manage this and also can cause unnecessary re-renders which will be even more expensive.

IMO there's one valid case for such a rule, if these data are passed to a component wrapped in `React.memo`, then we'd need to always wrap these operations in `useMemo`, `useCallback` etc. to preserve the reference between re-renders.

**Comment by ljharb** [comment]
and to be clear, i do believe in https://attardi.org/why-we-memo-all-the-things/, but i don't think an eslint rule is the best way to make it happen :-)

**Comment by shamilovtim** [comment]
Appreciate the perspectives here 👍. Closing as I think we've reached a consensus.
