### ISSUE TITLE
[TypeScript] jsx-no-leaked-render false positives with boolean types

### ISSUE THREAD

**Issue by SimonSchick** [jsx-eslint/eslint-plugin-react#3298]
I'm unsure as how far TS support goes for this package but this rule causes a lot of false positives when the type of the checked variable is already a bool, adding an extra `!!` is kind of annoying (albeit not a deal breaker).

Would it be possible to add support for type checking this rule?

**Comment by ljharb** [comment]
Yes. This is a duplicate of #3292.
