### ISSUE TITLE
Documentation Clarity for react/require-default-props

### ISSUE THREAD

**Issue by acgrant** [jsx-eslint/eslint-plugin-react#3301]
In YAML, I was unable to get the following to work:
```yaml
react/require-default-props:
  - error
  - functions: 'defaultArguments'
```
The documentation supports the use of the `functions` key which I'm fine with; however, when I attempt to utilize this option, I encounter the following error: `Value {"functions":"defaultArguments"} should NOT have additional properties.`.

**Comment by ljharb** [comment]
That's probably because the `functions` option was added in v7.30.0, and you're using a version older than that.

On github, in every project, always be sure you're looking at the docs on a release tag, and not on master/main.

**Comment by acgrant** [comment]
> That's probably because the `functions` option was added in v7.30.0, and you're using a version older than that.
> 
> On github, in every project, always be sure you're looking at the docs on a release tag, and not on master/main.

Thank you, I downloaded the latest of both "eslint-plugin-react" and "eslint", and it did the trick. I'll have to keep my eyes out for that.
