### ISSUE TITLE
False positive: react/no-multi-comp

### ISSUE THREAD

**Issue by BenjaminWFox-MuleSoft** [jsx-eslint/eslint-plugin-react#3343]
I have a `.ts` file with a handful of arrow functions returning null `() => null` that's getting flagged for `react/no-multi-comp`. Simplified example:

<img width="243" alt="Screen Shot 2022-07-21 at 3 13 30 PM" src="https://user-images.githubusercontent.com/104960760/180324005-ff6c2fbd-c57c-4175-8ee4-1bd397cd3030.png">

This is recent, happened when upgrading from 7.26.1 -> 7.30.1

**Comment by ljharb** [comment]
I believe this will be fixed by #3331 in the next release.
