### ISSUE TITLE
Prefix setting for hook-use-state

### ISSUE THREAD

**Issue by AviDuda** [jsx-eslint/eslint-plugin-react#3352]
I'm currently refactoring some code so I wanted to set this for now: `const [locale, _setLocale] = useState("en")` without using `setLocale` in the code.
I'm using the @typescript-eslint/no-unused-vars rule with `"varsIgnorePattern": "^_"` which allows me to have an unused var, but the hook-use-state rule is (fairly) complaining "useState call is not destructured into value + setter pair".

I'd like to see a setting for the hook-use-state rule to allow a regex prefix (and possibly a suffix).

**Comment by ljharb** [comment]
That seems like a lot of complexity to add as opposed to just using an eslint override comment in this one place?

**Comment by AviDuda** [comment]
I understand that it's easy to disable the rule for one-off changes like this. Maybe a setting isn't needed then.
Would you consider allowing an underscore prefix without any setting? This would play well with e.g. TypeScript's `noUnusedLocals` setting. Of course, state without a way to set state is useless, but as in my example with locale, it makes sense to temporarily write it like this with a prefix so it's obvious that it's something what needs to be eventually changed. It's always nicer to have defaults like this rather than putting `eslint-disable-next-line` in code and then forgetting about it.

**Comment by ljharb** [comment]
https://npmjs.com/eslint-plugin-eslint-comments may be helpful there?

**Comment by AviDuda** [comment]
I wasn't aware about this plugin, so thank you for the link. It works for my use case.
