### ISSUE TITLE
react/no-unknown-property throws on valid properties

### ISSUE THREAD

**Issue by AhmadMayo** [jsx-eslint/eslint-plugin-react#3380]
I recently upgraded eslint-plugin-react from v7.30.1 to v7.31.2, and when I tried to build, the rule started throwing on valid properties like key, viewBox, fill, d, and other SVG related properties - and none of the in kebab case, or contains a colon in their name.

eslint version: 8.23.0
nextjs version: 12.2.5

![image](https://user-images.githubusercontent.com/15085304/188234070-ec9124a9-1d7d-4f6b-96a9-9e6522a52fcb.png)

**Comment by mjchang** [comment]
Also getting this for other svg properties as well
- stroke
- strokeWidth
- strokeLinecap
- strokeLinejoin
- transform
- clipRule
- x1
- x2
- y1
- y2

**Comment by AhmedBHameed** [comment]
I confirm the issue.

**Comment by AhmadMayo** [comment]
@mjchang @AhmedBHameed when i commented this line from my eslint config, the issue seized to occur.
```
  extends: ["plugin:@next/next/recommended"],
```
Do you use next too? can you confirm if this resolves the issue for you too? if so, then the problem is related to next's plugin

**Comment by mjchang** [comment]
I don't use next. I use airbnb's eslint which includes this.

**Comment by peter-resmed** [comment]
![image](https://user-images.githubusercontent.com/109127976/188237711-ba5e892e-cc5e-4785-a0e5-9624bf306da5.png)
same issue

**Comment by AhmedBHameed** [comment]
@AhmadMayo 

I do use nextjs.I have default project extends
```json
{
	"extends": ["next/core-web-vitals"]
}
```

Which also causing eslint to complain.

I guess removing my line means ignoring eslint completely? However, the build run successfully when removing the line from `.eslintrc.json`

I reverted the update from v7.30.1 to v7.29.4 and the app return back to live.

I would say that might be a bug with the new version maybe?

**Comment by AhmadMayo** [comment]
@AhmedBHameed maybe. It's occurring randomly for me now. reverting back to version 7.29 didn't resolve the issue for me.

**Comment by AhmedBHameed** [comment]
@AhmadMayo 

Did you revert back your `yarn.lock` & `package.json`? Also did you delete both `node_modules` and `.next` before installing a fresh deps with `yarn`?

Try this and then build again.
That is what i did.

**Comment by AhmadMayo** [comment]
@AhmedBHameed same errors. I'll turn off the rule until I figure out what's going on.

**Comment by grybykm** [comment]
Downgrade to version 7.31.1. This is a breaking change and regression in version 7.31.2.

`npm i eslint-plugin-react@7.31.1 -D`

**Comment by ljharb** [comment]
Thanks all; I'm on it and will release a v7.31.3 soon.

@grybykm It's not a "breaking change" if it's not intentional, it's just a bug. Dial it back.

**Comment by ljharb** [comment]
cc @sjarva; seems #3377 has an issue. If you come up with a roll-forward fix before I get to the revert, I'd prefer to do that.

**Comment by apteryxxyz** [comment]
This also happens in `meta` tags with the `property` property, breaking usage of Open Graph.
(`<meta property="og:type" content="website" />`)

**Comment by AhmadMayo** [comment]
@ljharb I think I can do it. Give me 30 mins

**Comment by ljharb** [comment]
@AhmadMayo awesome, i've already got the test cases:
<details>
<summary>test cases</summary>

in "valid":
```jsx
    { code: '<svg key="lock" viewBox="box" fill={10} d="d" stroke={1} strokeWidth={2} strokeLinecap={3} strokeLinejoin={4} transform="something" clipRule="else" x1={5} x2="6" y1="7" y2="8"></svg>' },
    { code: '<meta property="og:type" content="website" />' },
```
</details>

if you can make modifications to the existing rule to allow these valid properties that'd be awesome :-)

**Comment by ljharb** [comment]
@AhmadMayo any update?

**Comment by AhmadMayo** [comment]
@ljharb added the properties and testing now

**Comment by AhmadMayo** [comment]
@ljharb PR ready

**Comment by sibartlett** [comment]
I get `Unknown property 'key' found` on other elements other than `<svg>`, such as `<a>` and `<span>`

**Comment by ljharb** [comment]
Certainly key and ref are special props on react elements that should never be warned on; I’ll handle that part.

**Comment by ljharb** [comment]
v7.31.1 has been set to "latest" for now, and v7.31.3 will be released within the next hour.

After it's released, and this is closed, please file *new* issues if you continue to see issues with v7.31.3. Thanks everyone, and sorry for the inconvenience!

**Comment by ljharb** [comment]
v7.31.3 is now released.

Please update, and file a _new_ issue if you're still seeing problems.
