### ISSUE TITLE
bug(react/no-unknown-property): What the hell?

### ISSUE THREAD

**Issue by ctjlewis** [jsx-eslint/eslint-plugin-react#3382]
You guys must've been *insaaaaaaanely* high when you released 7.31.2.

> @grybykm It's not a "breaking change" if it's not intentional, it's just a bug. Dial it back.

Lmfao okay. @ljharb, my advice is to test things before releasing them and not engage in bug denialism when people are kind enough to report them. We all know what he meant. Filing a duplicate just to annoy you.

See also: #3380

---

#### Throwing for `key` prop, valid on all `React.Component`
<img width="599" alt="image" src="https://user-images.githubusercontent.com/1657236/188252314-70595aa3-96f8-45a2-83ea-707ab4e5e925.png">

#### Throwing for various SVG props

<img width="599" alt="image" src="https://user-images.githubusercontent.com/1657236/188252284-7a8c2bae-dfc9-4078-b090-3a1a83097e23.png">

**Comment by ljharb** [comment]
Congrats, your hostile behavior just got you blocked.
