### ISSUE TITLE
`no-direct-mutation-state` for functional components

### ISSUE THREAD

**Issue by tim-hilt** [jsx-eslint/eslint-plugin-react#3387]
Some of our coworkers don't really grasp the concept of type-safety and registering state via the `useState`-hook.

Unfortunately the existing `no-direct-mutation-state`-rule is only working for class-components. Would it be possible to adjust this rule to also work for functional components?

**Comment by ljharb** [comment]
How would that work exactly? Function components don’t have a `this` to store state in.

**Comment by tim-hilt** [comment]
I haven’t written any real parsers yet, so I don’t know the technical details of implementing this.

So you think it’s rather impossible?

**Comment by ljharb** [comment]
Sorry, I'll try to be clearer.

How would it be possible for a functional component to have state at all? I'm saying I think it's impossible to create code that would violate this rule. Can you provide some examples?

**Comment by tim-hilt** [comment]
Sure!

const [count, setCount] = useState(0);

Maybe I misunderstood the actual meaning of useState? I always had the impression that this state is part of the component that introduced it!

**Comment by ljharb** [comment]
Ok - so in that case, are you asking for a rule that prevents mutating or reassigning `count`?

The latter is doable (but that’s what const is for) but the former is impossible if the variable is passed into a function

**Comment by tim-hilt** [comment]
I thought about both actually. I recently saw code like this, which lead me to ask this question:

const [flower, setFlower] = useState({color: „red“, size: 2});
flower.isVisible = true;

This could have been circumvented by using type-safety. However this couldn’t:

flower.size = 5;

(BTW, typing on my phone where I don’t have backticks available)

**Comment by ljharb** [comment]
While that's true, mutation of *all* kinds is an antipattern in react, so I'm not sure there's much value in a rule that special-cases just the state value from `useState`.

**Comment by tim-hilt** [comment]
Well, no-direct-mutation-state exists and essentially does the same thing, only for a class-component. However I understand, that that's very hard to implement. In this case all props of a component or items in a context would also have to be traced back to ensure the rule is working properly.

**Comment by ljharb** [comment]
That works because class components _have_ state - functional components simply don't, despite the confusing name of the `useState` hook (`useState` provides state for an *element*, which isn't the same thing as a class component's instance state).

If someone can make a PR with tons of test cases that actually traces all of these possibilities, and has zero false positives, i'd love to review it, but since I don't think that'll be possible in a practical sense, I'm going to close this for now.
