### ISSUE TITLE
[react/no-unknown-property] does not recognize `<td valign={...}`

### ISSUE THREAD

**Issue by simPod** [jsx-eslint/eslint-plugin-react#3389]
> Unknown property 'valign' found  react/no-unknown-property

```tsx
<td colSpan={colSpan} valign="middle">
  foo
</td>
```

`valign` is valid property on `td`

**Comment by sjarva** [comment]
[MDN has marked `valign` as deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td#attr-valign) and recommends using `vertical-align` instead.

**Comment by ljharb** [comment]
I think it should; deprecated is known.
