### ISSUE TITLE
no-unknown-property & styleName attribute (v7.31.6)

### ISSUE THREAD

**Issue by mcrawshaw** [jsx-eslint/eslint-plugin-react#3392]
React CSS Modules uses the `styleName` attribute (https://github.com/gajus/babel-plugin-react-css-modules). Not sure if this is standard enough to be included...

`<div styleName="styles.container" />`

Thanks,
Mark.

**Comment by ljharb** [comment]
I think this is in the same category as emotion's `css` attribute - both are utterly nonstandard, and neither should be used without a `data-` prefix, so the best approach is for you to add it to `ignore` in your rule config.
