### ISSUE TITLE
[no-unknown-property] data-* attributes should be allowed to have uppercase letters as well

### ISSUE THREAD

**Issue by HJain13** [jsx-eslint/eslint-plugin-react#3395]
Technically HTML tags and their attributes are case insensitive [[1]](http://w3c.github.io/html-reference/documents.html#case-insensitivity). But React types generally prevent usage of the uppercase/mixed case version of the tags and attributes as it conflicts with other established conventions (eg: treating tags with the first letter uppercase as a component in JSX). The typings for React also error out for uppercased attributes.

However, data-attributes are special in this regard; From what I can see `data-testId` is considered to be valid attribute even by react (though it's automatically lowercase by the browser) ([TS enabled react sandbox](https://codesandbox.io/s/data-attributes-case-insensitivity-n10pt7)). Right now the lint rule creates a false positive for this and I am not sure if that should be the case.

**Comment by ljharb** [comment]
for tags, not generally - jsx explicitly prevents it.

For attributes, there's a bunch of patterns - some are case sensitive, some case-insensitive. `data-testId` is a perfectly valid attribute - because it _works_, even if the browser normalizes it.

**Comment by HJain13** [comment]
> data-testId is a perfectly valid attribute - because it works, even if the browser normalizes it.

Right, but what I meant to say was that: the lint rule throws an error for it. 

<img width="795" alt="image" src="https://user-images.githubusercontent.com/6277011/188459786-d46e4a18-6db3-48f3-9eed-842bc5baa853.png">

The relevant code due to which it throws an error (the regex doesn't have A-Z)

<img width="673" alt="image" src="https://user-images.githubusercontent.com/6277011/188459992-c15d6669-6c09-468f-8ae9-b72a16ee7bf0.png">

**Comment by ljharb** [comment]
hmm - https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-* says
> The name must not contain any capital letters.

but i guess React and TS lowercase everything to meet that requirement. I'll update.
