### ISSUE TITLE
Unknown Property Issue with 7.31.6

### ISSUE THREAD

**Issue by djaffer** [jsx-eslint/eslint-plugin-react#3396]
Getting the following errors with the recent upgrade.
![image](https://user-images.githubusercontent.com/5740725/188371025-b500f45a-444c-4a9c-aae2-4ff05e0cb2a6.png)

**Comment by ljharb** [comment]
`download` was fixed in #3394.

**Comment by ljharb** [comment]
Can you elaborate on which element has `underline`?

**Comment by djaffer** [comment]
Material ui  https://v4.mui.com/api/link/

**Comment by ljharb** [comment]
On what element? You didn’t provide any code. Can you file a new issue for that?

**Comment by djaffer** [comment]
It is a link what source you need that for 
```
import { Link } from '@material-ui/core';
<Link href="https://github.com" underline="none">test</Link>
```

The build is failing now too.

**Comment by ljharb** [comment]
Have your settings configured Link to act as an a tag?

If so, since underline isn’t a standard link property, you’ll have to add “underline” to your ignore config for this rule.

**Comment by djaffer** [comment]
yes if you dont provide anything it works as an a tag.

**Comment by djaffer** [comment]
Will it be like this?  
 ```
 "react/no-unknown-property":[1,"underline"],

```

**Comment by ljharb** [comment]
Yes to both. No idea why it doesn’t work.

**Comment by djaffer** [comment]
only worked in eslintrc.js not in eslintrc.json
