### ISSUE TITLE
Missing controlsList property

### ISSUE THREAD

**Issue by Meemaw** [jsx-eslint/eslint-plugin-react#3397]
` error  Unknown property 'controlsList' found  react/no-unknown-property`

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/controlsList

**Comment by ljharb** [comment]
What version of the plugin are you using? That should be fixed in v7.31.6, in #3390.

**Comment by Meemaw** [comment]
I think there is a typo in there. `controlsList` vs `controlList`

**Comment by ljharb** [comment]
Thanks, fix will land soon.
