### ISSUE TITLE
react/no-unknown-property stopped supporting 'download' on <a /> tag  

### ISSUE THREAD

**Issue by fila90** [jsx-eslint/eslint-plugin-react#3399]
`Unknown property 'download' found  react/no-unknown-property`

This is perfectly valid attribute for a tag per [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download)
It worked nicely before the `7.31.6` update

**Comment by alinsimoc** [comment]
This has been fixed in #3394. I suppose it will come out with the next release.

**Comment by francofantini** [comment]
Hi @alinsimoc 👋 
Do you have a ETA on the next release?

**Comment by ljharb** [comment]
I will release the next patch sometime today.
