### ISSUE TITLE
react/no-unknown-property: invalid property `noModule` found on script tag

### ISSUE THREAD

**Issue by sarahp06** [jsx-eslint/eslint-plugin-react#3414]
Hello,

We have just gone from version `7.31.1` to `7.31.6`.  Now the `react/no-unknown-property` rule is reporting the `noModule` property of an `script` tag as invalid although it has worked correctly before.  Is this expected?

Thanks!

**Comment by alopix** [comment]
Looking at mdn, it looks like `nomodule` should be a valid HTML attribute on `script`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-nomodule
