### ISSUE TITLE
[react/no-unknown-property] Unknown property 'align'

### ISSUE THREAD

**Issue by tipleavalentin** [jsx-eslint/eslint-plugin-react#3425]
Hi!
There is an issue that still persists after the last minor updates:

warning  Unknown property 'align' found  react/no-unknown-property

Ex: <td align="center">{index + 1}</td>

Packages:
eslint-plugin-react: 7.31.7
eslint: 8.23.0

Can you please check? 
Thanks

**Comment by ljharb** [comment]
On what tag?

**Comment by ljharb** [comment]
nvm, i'll add it on all supported ones. note that "align" is deprecated, alignment should be done with CSS.

**Comment by tipleavalentin** [comment]
Sorry for the late reply. I pasted the code but the tag was removed.
It was a tabla data - td tag.
I didn't know it was deprecated, just checked, I guess you can leave it that way, I'm not using it that much.
Thanks!
