### ISSUE TITLE
Add react/jsx-no-constructed-context-values to recommended rules

### ISSUE THREAD

**Issue by mohd-akram** [jsx-eslint/eslint-plugin-react#3427]
I think this is a very impactful rule as this issue can have a significant impact on performance.

**Comment by ljharb** [comment]
Adding anything to that list is a breaking change, and it’s unlikely we’ll ever have one, but certainly if we ever do, the entire list of recommended rules will be thoroughly audited.

**Comment by mohd-akram** [comment]
I was looking at the last major release, and it was five years ago. Perhaps the library is due for a new release. I'm sure many simply use the `recommended` list and I was surprised to find that very few rules are in it.

**Comment by ljharb** [comment]
My recommendation is to use the Airbnb config.
