### ISSUE TITLE
Invitation to move to official `eslint-community` org

### ISSUE THREAD

**Issue by MichaelDeBoey** [jsx-eslint/eslint-plugin-react#3430]
It's up to you —@ljharb—, but if you'd like, you're welcome to transfer this repository to the official [`@eslint-community` organization on GitHub](https://github.com/eslint-community).

As you can read in [the '`@eslint-community` GitHub organization' RFC](https://github.com/eslint/rfcs/tree/main/designs/2022-community-eslint-org), the goal of this new org is to have a place where community members can help ensure widely depended upon ESLint related packages stay up to date with newer ESLint releases and doesn't hold the wider community back without depending on one person's GitHub/`npm` account.

Again, totally up to you. I just want you to know we appreciate all you've done and you're welcome to join the organization if you like.

**Comment by ljharb** [comment]
https://github.com/jsx-eslint/jsx-ast-utils/issues/121
> Thanks! I think anything that already has an org is probably ideal to remain there. I would hope that providing backup github/npm access to the community org's leadership would be sufficient to be considered "part of it", including funding, but that can be discussed separately.

**Comment by ljharb** [comment]
See https://github.com/jsx-eslint/jsx-ast-utils/issues/121#issuecomment-1242995999
