### ISSUE TITLE
`react/no-unknown-property`: Unknown property 'defaultChecked' found in `input`

### ISSUE THREAD

**Issue by recallwei** [jsx-eslint/eslint-plugin-react#3432]
An error occurred when I added the property `defaultchecked` in the `input` element.

<img width="664" alt="image" src="https://user-images.githubusercontent.com/62941121/189565829-ffb7adba-0267-4654-a726-fafa904602a6.png">

Here is my eslint version and config file:

<img width="843" alt="image" src="https://user-images.githubusercontent.com/62941121/189565879-97fbdf3a-af79-4109-b3b7-7c333b0ca110.png">
<img width="279" alt="image" src="https://user-images.githubusercontent.com/62941121/189565924-ae3055b1-6b60-43b4-b1e8-180c8e6c7ecb.png">

**Comment by ljharb** [comment]
That’s what’s in package.json; what’s in node_modules?

**Comment by recallwei** [comment]
Thanks! In vscode, I tried to restart the ESLint Server, and then the error disappeared.
