### ISSUE TITLE
dialog element onClose has react/no-unknown-property

### ISSUE THREAD

**Issue by rpearce** [jsx-eslint/eslint-plugin-react#3436]
[The `<dialog>` element has a `close` event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/close_event), and with a recent update to this package (somewhere between `7.31.0` and `7.31.8`), it seems that `<dialog onClose` is now triggering `react/no-unknown-property`.

Was this something that was intentionally done? If so, and if y'all have time, could you help me understand the thinking behind it?

Thanks for your time!

**Comment by ljharb** [comment]
Nope, just a bug. Thanks for reporting.

**Comment by ljharb** [comment]
This was broken in v7.31.2, and will be fixed in v7.31.9 once it's released (which i plan to do in the next day or three).

**Comment by rpearce** [comment]
Thank you! 🎉
