### ISSUE TITLE
npx eslint --fix not working for react/jsx-sort-props 

### ISSUE THREAD

**Issue by pradumn26** [jsx-eslint/eslint-plugin-react#3437]
## Project and eslint setup details
**package.json**
```
"react-scripts": "^4.0.3",

"eslint": "^7.11.0",
"eslint-plugin-react": "^7.31.8",
```

**.eslintrc.js**
```
module.exports = {
  env: {
    jest: true
  },
  globals: {
    page: true,
    browser: true,
    context: true,
    jestPuppeteer: true
  },
  extends: ['react-app', 'react-app/jest'],
  rules: {
    'import/no-anonymous-default-export': 'off',
    'no-unused-vars': 'warn',
    'react/jsx-sort-props': [
      1,
      {
        callbacksLast: true,
        shorthandFirst: true,
        multiline: 'last',
        ignoreCase: true
      }
    ]
  }
};
```

## Problem
The errors are showing up but cannot fix them automatically with `npx eslint --fix`

## Expected behaviour 
After reading the docs on your [git repo](https://github.com/jsx-eslint/eslint-plugin-react), i am expecting that errors from this rule can be fixed via eslint fix command. After running this command this extension should go to all files with errors and fix them by itself and save changes.

## What's happening
Nothing happens after running eslint fix command
<img width="1123" alt="Screenshot 2022-09-23 at 12 22 55 AM" src="https://user-images.githubusercontent.com/20491334/191828371-414a2175-2c06-4396-8d12-2f722a6db5e3.png">

**Comment by ljharb** [comment]
Try setting it to 2 (error) instead of 1 (warn).

Also, try `npx eslint . --fix` (note the dot).

If neither of those works, please link me to a repro repo.

**Comment by pradumn26** [comment]
checking

**Comment by pradumn26** [comment]
trying `npx eslint . --fix` works 👍👍

**Results**
It works for both 1 and 2

**Suggestion**
Please mention in your documentation meaning of these enums 1 and 2.

**PS**: Thanks a lot for replying so fast. I have never experienced this sort of response on an issue that i raised on popular repos. Keep it up 👍

**Comment by ljharb** [comment]
1 is "warn" and 2 is "error"; both are standard parts of eslint config that are documented by eslint itself, as is the need to pass a path to eslint ("." means the current directory, and is the best approach in my experience).

Glad you got it working!

**Comment by pradumn26** [comment]
Will try lower my noob level, by grinding more 😬.
