### ISSUE TITLE
Allow nested destructuring with `react/hook-use-state`

### ISSUE THREAD

**Issue by philer-jambit** [jsx-eslint/eslint-plugin-react#3443]
State is not always flat and sometimes it can make sense to destructure it directly. Example:

```js
const [{foo, bar, baz}, setFooBarBaz] = useState({foo: "omg", bar: "wtf", baz: "bbq"})
const [[index, value], setValueWithIndex] = useState([0, "hello"])
```

Note that in these cases the setter name can not be symmetrical to the destructured variables.

It would be nice if `react/hook-use-state` permitted this use case (maybe optional?).

Either way, thanks for the great work! :+1:

**Comment by ljharb** [comment]
That definitely seems like a reasonable option to add ("allowDestructuredState"?)
