### ISSUE TITLE
`react/no-unknown-property` think `directory` and `webkitdirectory` of `input` are unknown property

### ISSUE THREAD

**Issue by tylim88** [jsx-eslint/eslint-plugin-react#3454]
![image](https://user-images.githubusercontent.com/5227509/194706509-18f117e9-710c-4e84-98e3-4af1874c28a7.png)
![image](https://user-images.githubusercontent.com/5227509/194706523-b902e91e-8301-4a3d-96e0-96bb8c980f7a.png)

**Comment by ljharb** [comment]
MDN lists `webkitdirectory`, but not `directory`, implying that the latter is in fact unknown and should be removed. Which browser respects it?

**Comment by ljharb** [comment]
Indeed, it seems like there's no standard for "directory", so it's best not to provide it at this time. I'll close this with a fix for `webkitdirectory`.
