### ISSUE TITLE
react/no-invalid-html-attribute Shouldn't be auto-fixable

### ISSUE THREAD

**Issue by Janpot** [jsx-eslint/eslint-plugin-react#3458]
The automatic fix that is performed by the `react/no-invalid-html-attribute` rule removes invalid values. I'd argue this is dangerous behavior as removing the value is probably not the intended outcome, I mean, I've put it there for a reason in the first place. Some examples:

- I have a typo in one of the values, auto-fix removes it instead of forcing me to correct it
- I have a [non-standard value](https://developers.google.com/search/docs/crawling-indexing/qualify-outbound-links) e.g. `rel="sponsored"`, I'd like to replace it with `nofollow` instead of automatically removing it. Or I'd like to add an ignore directive to allow for it.

**Comment by ljharb** [comment]
Yes, I agree it should be a suggestion and not an autofix. A PR to fix that is welcome.

**Comment by himanshu007-creator** [comment]
Hi, i would like to give it a try

**Comment by ljharb** [comment]
Go for it!
