### ISSUE TITLE
Crash for master branch when extending "plugin:react/all" in eslintrc

### ISSUE THREAD

**Issue by golopot** [jsx-eslint/eslint-plugin-react#3461]
In master branch of this plugin, extending `plugin:react/all` in eslintrc cause a crash. This bug comes from #3429.

**Reproduction:**
```sh
mkdir demo-config-bug
cd demo-config-bug
npm init --yes
npm i eslint jsx-eslint/eslint-plugin-react#master
touch a.js
echo '{"extends": ["plugin:react/all"]}' > .eslintrc.json
npx eslint .
```
**Result:**
Oops! Something went wrong! :(

ESLint: 8.25.0

Error: ESLint configuration in .eslintrc.json » plugin:react/all is invalid:
	- Unexpected top-level property "languageOptions".

@jjangga0214

**Comment by ljharb** [comment]
Thanks for catching that. The hope was that we can use the same imports in both config systems.

**Comment by ljharb** [comment]
@golopot can you try changing `node_modules/eslint-plugin-react/configs/all.js` to add `Object.defineProperty(module.exports, 'languageOptions', { enumerable: false });` as the last line, and try again?

I'm wondering if making it non-enumerable will "hide" it from the legacy config's validation.

**Comment by golopot** [comment]
@ljharb Adding that line fixed the bug.

**Comment by ljharb** [comment]
Thanks@

@jjangga0214 can you confirm that with that line added, the new config system still works?
