### ISSUE TITLE
Why jsx-no-bind rule is still enabled by default?

### ISSUE THREAD

**Issue by arashmanteghi** [jsx-eslint/eslint-plugin-react#3472]
I recently investigated using the inline function in the render phase. For example, inline function on event handler. Some think like this:

```
const handleClick = () => {
  console.log('clicked);
}

<button onClick={handleClick}>Submit</button>
```

Based on the [`jsx-no-bind`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md) rule, we must use `useCallback` in this situation, but as far as I know, `useCallback` has its own use case, and we shouldn't use it for every function, especially when it comes to hooks components. After reading [Kent C. Dodds blog post related to `useCallback`](https://kentcdodds.com/blog/usememo-and-usecallback) and [Ryan Florence's post about inline function](https://reacttraining.com/blog/react-inline-functions-and-performance/) and [Benedikt Meurer post about the performance of function.prototype.bind](https://benediktmeurer.de/2015/12/25/a-new-approach-to-function-prototype-bind/), I can't understand the reason of existing this rule.

Could someone please explain it to me?

**Comment by ljharb** [comment]
Nothing's enabled by default - you have to be using a config that enables it.

You should generally use useCallback for every callback imo - see https://attardi.org/why-we-memo-all-the-things/ - but if you don't want to, feel free to disable the rule.
