### ISSUE TITLE
`jsx-newline` puts line breaks between comments and new JSX elements

### ISSUE THREAD

**Issue by Sreejit7** [jsx-eslint/eslint-plugin-react#3478]
I have the `jsx-newline` rule turned on, which when run with the `--fix` option, puts line breaks between any comments (including eslint-disable comments) and JSX elements, thus undoing the whole point of using comments. 

Let's say I have something like this:

```jsx
<Element as="header" marginBottom="micro">
        {/* eslint-disable-next-line react/jsx-sort-props */}
        <Heading as="h6" align="right">
            Transaction value
        </Heading>
<Element>
```

The `jsx-newline` rule puts a line break between the eslint-disable comment and <Heading />, therefore causing the `eslint-disable-{some rule}` to stop working.

Can we handle putting line breaks between comments & new JSX elements?

I saw something similar in #2926 (which was closed earlier as completed) but that doesn't work properly as of `v7.31.10`

**Comment by sujan-s** [comment]
To demonstrate the above comment—

What we need—
![Screenshot 2022-11-02 at 12 04 03 PM](https://user-images.githubusercontent.com/19920532/199415966-1f030edf-b197-4bb7-92fe-76f84cad8adf.png)

But what actually happens—
![Screenshot 2022-11-02 at 12 04 17 PM](https://user-images.githubusercontent.com/19920532/199416106-24c05a7e-0dd9-4940-8a9f-1bb5a0f17494.png)

Which we obviously don’t want.

**Comment by ljharb** [comment]
If this is new behavior in .10, then it’s a bug (cc @ROSSROSALES), and we should fix it.

**Comment by Sreejit7** [comment]
@ljharb it's not a new behavior in .10, we were using 7.31.8, upgraded to .10

**Comment by ROSSROSALES** [comment]
@ljharb Thanks for pinging me, I can try and take a look into it
