### ISSUE TITLE
Rule undefined-useeffect-dependency

### ISSUE THREAD

**Issue by PMLP-novo** [jsx-eslint/eslint-plugin-react#3480]
A notorious bug with useEffect is to make a useEffect without definining dependencies and having the useeffect running all the time.
Like:
```
useEffect(() => {
    // some code
  });

```
instead should be 

```
  useEffect(() => {
    // some code
    // eslint-disable-next-line react-hooks/undefined-dependency
  });
```
or if possible
```
  useEffect(() => {
    // some code
  }, undefined); 
``` 
To make it clear that this is what is intended. 
A name for the rule could be `undefined-useeffect-dependency`
I don't know if this should be toggled on by default. I would prefer it, since I have not seen a real world example where it made sense to not define the dependentcies of a use effect

**Comment by ljharb** [comment]
This seems like something that should go in eslint-plugin-react-hooks, since it's specific to a single hook - this is the react plugin.
