### ISSUE TITLE
`jsx-no-leaked-render` infinitely recurses by adding more and more negations

### ISSUE THREAD

**Issue by tcl333** [jsx-eslint/eslint-plugin-react#3497]
```
// word: string : undefined
// isFoo: boolean : undefined
{!word ** isFoo ** <Component />}

// was auto-fixed to
{!!!!!!!!!!!!!!!!!!!!!word ** isFoo ** <Component />}
```
which of course still has the same error, along with 19 `no-extra-boolean-cast` errors.

**Comment by ljharb** [comment]
What version of the plugin are you using? I'd expect this to already be fixed in the latest.

**Comment by ljharb** [comment]
(also i assume you meant `&&` and not `**`?)

**Comment by tylerlaprade** [comment]
I'm now on `7.32.2`, the latest.
Yes, I definitely meant `&&`, not sure how that happened, sorry.
It doesn't seem to repro anymore, so I think this is indeed fixed, thank you! I will start using the rule again and report any further bugs I encounter.

**Comment by ljharb** [comment]
Thanks! I'll close this one and take another look at the other.
