### ISSUE TITLE
[Bug]: no `eslint-plugin-react/configs/recommended` exported

### ISSUE THREAD

**Issue by chenxsan** [jsx-eslint/eslint-plugin-react#3512]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

Hi there, I was trying to use `eslint-plugin-react` 7.31.11 with the new ESLint configuration `eslint.config.js`. And I noticed the readme here says I can import `eslint-plugin-react/configs/recommended` per https://github.com/jsx-eslint/eslint-plugin-react#shareable-configs-1, but that doesn't hold true according to https://github.com/jsx-eslint/eslint-plugin-react/blob/master/index.js#L29

Seems I can only use `eslintPluginReact.configs.recommended` after `import eslintPluginReact from 'eslint-plugin-react'` at the moment.

I can see a `configs` folder here https://github.com/jsx-eslint/eslint-plugin-react/tree/master/configs, but pnpm doesn't install it:

<img width="433" alt="" src="https://user-images.githubusercontent.com/1091472/209561165-63e0793d-f6be-447a-a8cd-79d9ae293617.png">

Maybe we should include it with the `files` list https://docs.npmjs.com/cli/v8/commands/npm-publish#files-included-in-package?

### Expected Behavior

`import recommended from 'eslint-plugin-react/configs/recommended'` to work fine as readme shows.

### eslint-plugin-react version

7.31.11

### eslint version

8.30.0

### node version

18.2.1

**Comment by ljharb** [comment]
That’s still unreleased. Everywhere on github, you have to read the docs on the latest release tag, not on master/main.
