### ISSUE TITLE
[Bug]: `no-object-type-as-default-prop` was not found

### ISSUE THREAD

**Issue by weishaodaren** [jsx-eslint/eslint-plugin-react#3518]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

in my .eslintrc, only `no-object-type-as-default-prop` didn't work

<img width="462" alt="image" src="https://user-images.githubusercontent.com/45391716/211455879-ab4884c8-e973-47aa-8661-c9f3a01e3c59.png">

<img width="854" alt="image" src="https://user-images.githubusercontent.com/45391716/211456122-009c8480-a21e-4894-8d4d-c0cf565ea961.png">

### Expected Behavior

document https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-object-type-as-default-prop.md

### eslint-plugin-react version

v7.31.11

### eslint version

v8.31.0

### node version

v16.16.0

**Comment by ljharb** [comment]
That's expected, since it's not released yet. Everywhere on github, you need to look at the docs for the latest tagged release, not for master/main.
