### ISSUE TITLE
Eslint rule react/destructuring-assignment automatic fix is not working

### ISSUE THREAD

**Issue by jonathan-vandal** [jsx-eslint/eslint-plugin-react#3531]
I'm using react 17 with npm 8 and I just added this rules to my eslintrc.js :

```js
  rules: {
    "react/destructuring-assignment": [2, "always"],
    ...

```
In my code I can see lot of errors now it's ok but when I press `ctrl + s` to save my file there is no automatic fix. I tried to use this command on my file npx eslint --fix src/views/Forms/myFile.jsx but there is no changes in my file I just have multiple errors in the output like : `error  Must use destructuring state assignment  react/destructuring-assignment`

In the [rule documentation](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/destructuring-assignment.md) there is this line :

This rule is automatically fixable by the --fix CLI option.

So I don't understand how can I do to apply the automatic fix on my project.

**Comment by ljharb** [comment]
Not every kind of error is autofixable, but some are. When the autofix doesn't fix a problem, it just means you have to do it manually.

**Comment by vladshcherbin** [comment]
Either docs `fixable` checkmark is incorrect or rule's `fix` functionality is not working

**Comment by ljharb** [comment]
Here’s at least one example in the tests of i

**Comment by vladshcherbin** [comment]
@ljharb good to know it's partly working, thank you

the docs give false impression of the code:

```js
const MyComponent = (props) => {
  return (<div id={props.id} />)
}
```

would automatically fix to:

```js
const MyComponent = ({ id }) => {
  return (<div id={id} />)
}
```

the only part it managed to fix is the `destructureInSignature` which is actually turned off (`'ignore'`) by default

**Comment by ljharb** [comment]
If it’s autofixing in a way that doesn’t match the config, please file a new issue for that.

If the docs are actually implying an autofix that isn’t there - as opposed to just showing the code that would pass - a PR would be most welcome.
