### ISSUE TITLE
[jsx-curly-brace-presence] template literals contains just expressions

### ISSUE THREAD

**Issue by taozhou-glean** [jsx-eslint/eslint-plugin-react#3537]
we enabled jsx-curly-brace-presence, but I am seeing patterns in some code like following:

```
<Comp label={`${componentLabel}`} />

// or

<Comp>
{`${someText}`}
</Comp>
```

which would be same as:

```
<Comp label={componentLabel} />

// or

<Comp>
{someText}
</Comp>
```

and this seems to be an ideal case to be caught by jsx-curly-brace-presence ;)

=> Found "eslint-plugin-react@7.32.2"
=> Found "eslint@8.34.0"

**Comment by ljharb** [comment]
I wasn't paying enough attention I guess, because these aren't actually the same.
