### ISSUE TITLE
[Bug]: change default option for `functions ` option in `react/require-default-props` rule

### ISSUE THREAD

**Issue by alvessteve** [jsx-eslint/eslint-plugin-react#3543]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

According to this [`issue`](https://github.com/facebook/react/pull/25699), in future version using `defaultProps` will be deprecated for functions components and not recommended for function components.

However, according the [`documentation`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/require-default-props.md#rule-options), function components still relies on `defaultProps`.

### Expected Behavior

Change the default value of the rule option to be `defaultArguments` instead of `defaultProps`

### eslint-plugin-react version

v7.31.11

### eslint version

v8.31.0

### node version

v18.12.1

**Comment by ljharb** [comment]
Until a version of React is released that contains this (unfortunate and unwise) change, there's no point in updating the docs.
