### ISSUE TITLE
Mailformed package error

### ISSUE THREAD

**Issue by rocketana** [jsx-eslint/eslint-plugin-react#3544]
`Mailformed package` error even after fresh install (`npm i  eslint-plugin-react`) or removing `node_modules` and reinstalling them from scratch. 

![image](https://user-images.githubusercontent.com/63323342/222880494-46f0df9d-3b25-4478-97dc-edcaee56b003.png)

eslint-plugin-react version 7.32.2
eslint version 8.35.0
node version 18.12.1

**Comment by ljharb** [comment]
That's a file shipped with the `resolve` package. It's also a test fixture in that package. Where did you get "malformed package error"?

I would suggest immediately distrusting any tool that's foolish enough to naively scan for any file called "package.json" in node_modules, even ones that aren't the root of a package.
