### ISSUE TITLE
[Bug]: Autofix do not work in `react/jsx-wrap-multilines`

### ISSUE THREAD

**Issue by coderaiser** [jsx-eslint/eslint-plugin-react#3545]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

```js
export default () => <h1>
    <span>
        hello
    </span>
</h1>;
```

Error reported: 
![image](https://user-images.githubusercontent.com/1573141/222895507-12b11df8-0a8a-464a-962d-f3961e390f10.png)

No fix applied

### Expected Behavior

Auto fix correct code to:

```js
export default () => (
    <h1>
        <span>
            hello
        </span>
    </h1>
);
```

### eslint-plugin-react version

v7.32.2

### eslint version

v8.35.0

### node version

v18.14.2

**Comment by ljharb** [comment]
It's not a bug that a rule doesn't autofix, to be clear - not all rules autofix.

That said, it'd be great to add autofixing to this rule.

**Comment by coderaiser** [comment]
I see that the rule has some code that does [autofix](https://github.com/jsx-eslint/eslint-plugin-react/blob/66b58dd4864678eb869a7bf434c72ff7ac530eb1/lib/rules/jsx-wrap-multilines.js#L182), also documentation mentioned this.

**Comment by ljharb** [comment]
ah yes, you're right, everything is passing a fixer, so there's something wrong here.

**Comment by burtek** [comment]
Tried replicating this, but it fixes that example piece of code correctly for me :thinking:

**Comment by ljharb** [comment]
@burtek with what config? The test case I can get passing autofixes to:
```js
        export default () => (<h1>
            <span>
                hello
            </span>
        </h1>);
```
(note the parens not being on their own lines)

**Comment by burtek** [comment]
Oh wait, missed the part where parens should be on separate lines. Will see if I can fix it quickly

**Comment by burtek** [comment]
Wait, but with what config @ljharb ? Default is `parens` so it works as expected. If I set `arrow: 'parens-new-line'` it autofixes correctly...

![image](https://github.com/jsx-eslint/eslint-plugin-react/assets/2940958/60f154e5-1d3f-48e2-a68c-26760947aeb1)
