### ISSUE TITLE
[Bug]: Autofix removes generic type parameter from components when using `react/jsx-first-prop-new-line`

### ISSUE THREAD

**Issue by Stekmo** [jsx-eslint/eslint-plugin-react#3546]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

Generic components have their generic parameter removed when auto fixing.

https://user-images.githubusercontent.com/22430302/223438876-11966b60-cdf5-4ce8-9cbf-8b096c2f1108.mov

It should not remove the generic argument.

I setup vscode to format on save. Alternatively `eslint . --ext .tsx,.ts` produces the same result.

My eslint config.
```
module.exports = {
  parser: "@typescript-eslint/parser",
  extends: [
    "plugin:compat/recommended",
    "plugin:react/recommended",
  ],
  env: {
    browser: true,
  },
  plugins: [
    "@typescript-eslint",
  ],
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: "module",
    tsconfigRootDir: __dirname,
    project: "./tsconfig.json",
    ecmaFeatures: {
      jsx: true,
    },
  },
  rules: {
    "react/jsx-first-prop-new-line": ["error", "multiline"],
  },
  settings: {
    react: {
      version: "detect", // Tells eslint-plugin-react to automatically detect the version of React to use
    },
    "import/internal-regex": "^components/|^lib/",
    polyfills: ["fetch", "Promise"],
  },
};
```

### Expected Behavior

It should keep the generic argument. E.g.
```
<DataTable<Items> fullscreen keyField="id" items={items}  />
```
Should become
```
<DataTable<Items> 
  fullscreen
  keyField="id"
  items={items}
/>
```

### eslint-plugin-react version

v7.32.2

### eslint version

v8.35.0

### node version

v16.15.1

**Comment by ljharb** [comment]
I'm not seeing it autofix at all - the code you provided passes. The code in the image is different, though, I'll try that.

**Comment by ljharb** [comment]
ok yeah thanks, i was able to repro it.
