### ISSUE TITLE
[Bug]: Excessive code changes done by --fix react/jsx-no-leaked-render

### ISSUE THREAD

**Issue by gersongoulart** [jsx-eslint/eslint-plugin-react#3551]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

When using `'react/jsx-no-leaked-render': ['error', { validStrategies: ['coerce', 'ternary'] }],` and running `eslint --fix` the resulting code changes go beyond what's required for the actual fix by also removing parentheses, causing excessive code diffs.

<img width="696" alt="Screenshot 2023-03-17 at 9 03 07 PM" src="https://user-images.githubusercontent.com/1100106/226071722-4f1ac20d-d142-4792-9e0f-21d2b12b6ca6.png">

I would expect the second hunk to be a single line change, just like the first hunk. Running this fix across a large codebase is unfeasible because the changes cannot be human-verified.

`eslint --fix` with `'react/jsx-no-leaked-render': ['error', { validStrategies: ['coerce', 'ternary'] }],`

### Expected Behavior

I'd expect no parentheses would be removed and no code-style to change. Other than the `!!` required to fix the issue, nothing else at all should change in the code.

<img width="696" alt="Screenshot 2023-03-17 at 9 09 34 PM" src="https://user-images.githubusercontent.com/1100106/226072053-1eafd9e8-fa16-4ad6-b7bb-536de0baba73.png">

### eslint-plugin-react version

7.21.5

### eslint version

8.35.0

### node version

16.13.1

**Comment by ljharb** [comment]
I agree with the parens, in particular because that is a much better style anyways :-)

**Comment by ljharb** [comment]
cc @akulsr0

**Comment by akulsr0** [comment]
As I can understand, is following expectations correct?

**Input:** 

```jsx
const MyComponent = () => {
    return (
      <>
        {someCondition && (
          <div>
            <p>hello</p>
          </div>
        )}
      </>
    )
}
```

**Current Output:**

```jsx
const MyComponent = () => {
  return (
    <>
      {!!someCondition && <div>
          <p>hello</p>
        </div>}
    </>
  )
}
```

**Expected Output:**

```jsx
const MyComponent = () => {
  return (
    <>
      {!!someCondition && (
        <div>
          <p>hello</p>
        </div>
      )}
    </>
  )
}
```

**Comment by ljharb** [comment]
Yep, that’s right.
