### ISSUE TITLE
Failed to load plugin 'react' declared in '.eslintrc.json': Cannot find module

### ISSUE THREAD

**Issue by kaykhan** [jsx-eslint/eslint-plugin-react#3559]
I've created a react native app using expo and installed eslint and prettier. However i noticed at the top of all files i get the following eslint error:

```
Error: Failed to load plugin 'react' declared in '.eslintrc.json': Cannot find module '/home/kay/kay/worldxp/node_modules/eslint-plugin-react/node_modules/resolve/index.js'
   Referenced from: /home/kay/kay/worldxp/.eslintrc.json
    eslint_d()
```

**eslintrc.json**

     {
        "env": {
            "browser": true,
            "es2021": true,
            "node": true
        },
        "extends": [
            "eslint:recommended",
            "plugin:react/recommended",
            "plugin:@typescript-eslint/recommended",
            "plugin:prettier/recommended"
        ],
        "overrides": [
        ],
        "parser": "@typescript-eslint/parser",
        "parserOptions": {
            "ecmaVersion": "latest",
            "sourceType": "module"
        },
        "plugins": [
            "react",
            "@typescript-eslint"
        ],
        "rules": {
            "prettier/prettier": "error",
            "indent": [
                "error",
                4
            ],
            "linebreak-style": [
                "error",
                "unix"
            ],
            "quotes": [
                "error",
                "double"
            ],
            "semi": [
                "error",
                "always"
            ]
        }
    }

**package.json**

```
...
  "dependencies": {
    "expo": "~48.0.9",
    "expo-constants": "~14.2.1",
    "expo-linking": "~4.0.1",
    "expo-router": "^1.4.3",
    "expo-status-bar": "~1.4.4",
    "react": "18.2.0",
    "react-native": "0.71.5",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-web": "~0.19.1"
  },
  "devDependencies": {
    "@babel/core": "^7.21.4",
    "@types/react": "~18.0.32",
    "@typescript-eslint/eslint-plugin": "^5.57.0",
    "@typescript-eslint/parser": "^5.57.0",
    "eslint": "^8.37.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.32.2",
    "prettier": "2.8.7",
    "typescript": "^5.0.3"
  },
```

**Comment by ljharb** [comment]
I see you’re using eslint_d; what happens with actual eslint?

**Comment by kaykhan** [comment]
Oh, that error goes away when moving from eslint_d to eslint, do you know why that is? 

---


Although im left with this error but i think this is a seperate issue.
```
 'React' must be in scope when using JSX eslint(react/react-in-jsx-scope
 ```
 
 on 
 
 ```
  <Stack.Screen
                options={{
                    title: params.name as string,
                }}
            />
```

**Comment by ljharb** [comment]
Nope, but I’d file it with eslint_d, since actual eslint is the source of truth.

That’s a separate issue, and means you need to import react in that file.
