### ISSUE TITLE
[Bug]: Invalid property 'onLoad' found on tag 'div'

### ISSUE THREAD

**Issue by abhijeetbhagat** [jsx-eslint/eslint-plugin-react#3562]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

i am trying to hide a `div` when another `div` loads. i am trying to do this using the `onLoad` property of the `div` element, which my ide intellisense also shows. however, i am getting an error.

the div looks like:
` <div onLoad={hideMainDiv} className="min-h-screen bg-page overflow-hidden">`

i am getting this error:
`Invalid property 'onLoad' found on tag 'div', but it is only allowed on: script, img, link, picture, iframe, object  react/no-unknown-property`

this is the command i use to build my project:
`npm run build`

### Expected Behavior

i should not get an error.

### eslint-plugin-react version

v7.32.2

### eslint version

v8.38.0

### node version

v18.14.0

**Comment by ljharb** [comment]
I'm relatively sure that divs can't actually get a load event, despite intellisense. Have you tested it in an actual browser?

**Comment by abhijeetbhagat** [comment]
ok, apologies! new to web ui programming and had no reason to believe that it wasn't supported. closing the issue.
