### ISSUE TITLE
[Bug]: checkContextObjects option in react/display-name hasn't been published

### ISSUE THREAD

**Issue by ysulyma** [jsx-eslint/eslint-plugin-react#3565]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

The [`checkContextObjects`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/display-name.md#checkcontextobjects-default-false) option of `react/display-name` is documented in this repo, and implemented in the code, but doesn't appear in the latest `eslint-plugin-react` published to npm.

### eslint-plugin-react version

v7.32.2

### eslint version

v8.35.0

### node version

v16.17.0

**Comment by ljharb** [comment]
Unreleased changes aren't a bug, and are a perfectly normal part of all software.

**Comment by ysulyma** [comment]
@ljharb it's unusual to have unreleased changes on the `master` branch. I think it should at least be removed from the docs until it's been released—I googled the `react/display-name` rule and arrived at the docs page which said I could use `checkContextObjects`, then spent 20 minutes or so trying to figure out why it wasn't working in my project.

**Comment by ljharb** [comment]
No, it's not unusual.

On every repo on github, you need to look at the docs for the tagged version you're using.
