### ISSUE TITLE
[Bug]: react/no-unused-prop-types returns no errors when using the spread operator in JSX element

### ISSUE THREAD

**Issue by david-martyn-ford** [jsx-eslint/eslint-plugin-react#3566]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

When using the spread operator within a JSX component, the rule `react/no-unused-prop-types` no longer detects any errors.

## Demo Code

`package.json`
```json
{
  "scripts": {
    "lint": "eslint Demo.tsx"
  },
  "private": true,
  "devDependencies": {
    "@types/react": "^18.2.0",
    "@typescript-eslint/parser": "^5.59.1",
    "eslint": "^8.39.0",
    "eslint-plugin-react": "^7.32.2",
    "typescript": "^5.0.4"
  },
  "dependencies": {
    "react": "^18.2.0"
  }
}
```

`.eslintrc.js`
```js
module.exports = {
  parser: "@typescript-eslint/parser",
  extends: ["plugin:react/recommended"],
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: "module",
    ecmaFeatures: {
      jsx: true
    }
  },
  settings: {
    react: {
      version: "detect"
    }
  },
  rules: {
    "react/no-unused-prop-types": 2
  }
};
```

`Demo.tsx`
```ts
import React from "react";

type Props = {
  foo: string;
  bar: string; // <-- unused prop
};

const Demo: React.FC<Props> = ({ foo }) => {
  return <div {...{}}>{foo}</div>;
};

export default Demo;

```

### With spread operator

No error is detected when a prop type is unused within the component a spread operator is used in an element for attributes.

<img width="761" alt="CleanShot 2023-04-28 at 10 48 47@2x" src="https://user-images.githubusercontent.com/1824649/235101336-17757fe2-b958-4e4c-b6b2-d8ddc6f406b1.png">

### Without spread operator

When removing the spread operator, the unused prop is detected
<img width="764" alt="CleanShot 2023-04-27 at 14 10 33@2x" src="https://user-images.githubusercontent.com/1824649/234857994-073c3ae4-d93f-4c9d-acad-69cfc598c081.png">

## Steps to reproduce

`yarn lint`

### Expected Behavior

`bar` should be marked as a linting error
<img width="635" alt="CleanShot 2023-04-27 at 14 08 06@2x" src="https://user-images.githubusercontent.com/1824649/234857454-7106d1bc-dbda-4c3a-b21a-51314e8261dd.png">

### eslint-plugin-react version

v7.32.2

### eslint version

v8.39.0

### node version

v18.11.0

**Comment by ljharb** [comment]
When you're spreading the *props* object, the rule intentionally stops warning on things, because if you're doing this (don't) you've basically given up on anyone, human or linter, from being able to figure out what's in that object by reading the code.

This specific case is weird because you're not spreading the props object, so I wouldn't expect this to affect anything.
