### ISSUE TITLE
[Bug]: [eslint] Plugin "react" was conflicted between "package.json

### ISSUE THREAD

**Issue by Codeprince001** [jsx-eslint/eslint-plugin-react#3571]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

First time setting up react application on my device and i try to run for the first time and i get this error

![react problem](https://user-images.githubusercontent.com/109921600/235972262-d3078b2f-b91a-48e8-84a2-ff9c4c5423f4.PNG)

[eslint] Plugin "react" was conflicted between "package.json » eslint-config-react-app » C:\Users\user\Documents\\ReactJS\first-app\node_modules\eslint-config-react-app\base.js" and "BaseConfig » C:\Users\user\Documents\\ReactJS\first-app\node_modules\eslint-config-react-app\base.js".

### eslint-plugin-react version

7.32.2

### eslint version

8.39.0

### node version

20.0.0

**Comment by ljharb** [comment]
CRA is largely deprecated and can’t be fixed without ejecting. You’ll have to eject, or install the version that it wants.
