### ISSUE TITLE
Feature Request: `no-unused-props` for functional components

### ISSUE THREAD

**Issue by silverwind** [jsx-eslint/eslint-plugin-react#3576]
Currently there exist two rules for unused props:

- [`no-unknown-property`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unknown-property.md) only checks a limited set of DOM properties
- [`no-unused-prop-types`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unused-prop-types.md) only works with legacy `prop-types`

I would suggest a new rule `no-unused-props` that works on all functional components. It would be incredibly useful. For example:

```jsx
const Foo = ({name}) => <div>{name}</div>
const Bar = () => <Foo name="foo"/> // ok
const Baz = () => <Foo unused="foo"/> // error: unknown property "unused"
```

**Comment by golopot** [comment]
It is hard for ESLint rules to work across files, so if the component is defined and used in different files the proposed rule would not work. For checking undefined props, typescript is a good solution. If you cannot use typescript, typescript `checkJs` is also quite good.

**Comment by silverwind** [comment]
Thanks for those pointers, I will definitely try TS for this, thought I wonder how well it can deal with this react-specific object form sytnax. And yes, it's a shame eslint plugins are mostly restricted to single files. The only plugin I know that works across files is `eslint-plugin-import`.

**Comment by ljharb** [comment]
This is indeed what propTypes and a type system are for, and not something that’s practical with linters.

**Comment by silverwind** [comment]
> This is indeed what propTypes and a type system are for, and not something that’s practical with linters.

I disagree: the precense/absence of of args is a linting concern, it has nothing to do with the arg types itself.

Type checking is of course best done via TS currently, or possible future type checkers that will support type annotations.

**Comment by ljharb** [comment]
The `Foo` component, if properly using propTypes, will report that at runtime (and in your tests).

**Comment by silverwind** [comment]
Got something working using [eslint-plugin-tsc](https://github.com/unlight/eslint-plugin-tsc) which runs the typescript compiler as a eslint rule, and it seem to do what I need:

```
unused.jsx
  3:25  error  Type '{ unused: string; }' is not assignable to type '{ name: any; }'.
  Property 'unused' does not exist on type '{ name: any; }'  tsc/config

**Comment by ljharb** [comment]
Seems like `npx tsc` would catch that also, but sure, that's also in the realm of types once you go cross-file (you should *also* use propTypes because they're much more powerful than TS)

**Comment by silverwind** [comment]
Yeah, `tsc` shows the same error and the plugin just translated these errors to eslint, and it also seems to be capable of checking across files.

propTypes, yes it would probably be better but so far I don't really see it worth the extra effort when all I want is simple existance checks. Maybe something for later.

**Comment by ljharb** [comment]
The value even with existence checks is that it's checked at *runtime* and in your tests, whereas a build-time type system is merely aspirational.
