### ISSUE TITLE
[Bug]: Fixer of `sort-prop-types` doesn’t respect `noSortAlphabetically` 

### ISSUE THREAD

**Issue by kripod** [jsx-eslint/eslint-plugin-react#3591]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

Unlike with `jsx-sort-props`, the `sort-prop-types` rule doesn’t respect the `{ noSortAlphabetically: true }` option passed when fixing the order of prop types.

When `"react/sort-prop-types": ["warn", { callbacksLast: true, noSortAlphabetically: true }]` is set, the example below:

```js
AccordionItem.propTypes = {
  open: PropTypes.bool,
  onClick: PropTypes.func,
  id: PropTypes.string,
};
```

Gets fixed as follows:

```js
AccordionItem.propTypes = {
  id: PropTypes.string,
  open: PropTypes.bool,
  onClick: PropTypes.func,
};
```

While the underlying `callbacksLast` issue is fixed, it appears that `noSortAlphabetically` isn’t respected by the fixer, just as seen in the source:

- https://github.com/jsx-eslint/eslint-plugin-react/blob/ae64aa8fa059fd2b4088642c1b591b8662e6ccc9/lib/rules/sort-prop-types.js#L178-L187
- https://github.com/jsx-eslint/eslint-plugin-react/blob/ae64aa8fa059fd2b4088642c1b591b8662e6ccc9/lib/rules/sort-prop-types.js#L109-L119

The `fixPropTypesSort` method doesn’t take a `noSortAlphabetically` parameter.

### Expected Behavior

The correct fix for the snippet above would be:

```js
AccordionItem.propTypes = {
  open: PropTypes.bool,
  id: PropTypes.string,
  onClick: PropTypes.func,
};
```

Only `onClick` should be moved to the bottom, leaving the order of non-callback props intact.

### eslint-plugin-react version

7.32.2

### eslint version

v8.43.0

### node version

v16.20.0

**Comment by caesar1030** [comment]
@kripod, @liharb I’d love to work on this

**Comment by ljharb** [comment]
@caesar1030 go for it, you can just put up the PR, no need to comment :-)
