### ISSUE TITLE
[Bug]: jsx-sort-props not working correctly when props are commented

### ISSUE THREAD

**Issue by catalinandreipreda** [jsx-eslint/eslint-plugin-react#3612]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

I extend eslintrc with "plugin:react-hooks/recommended" and have the rule "react/jsx-sort-props": "warn"

With the ESLint VSCode extension I'm able to reorder props via 'Quick fixes'. This generally works correctly, but when there is a comment on the line following the out of order prop, the quick fix either does nothing or the sorting isn't correct.

![image](https://github.com/jsx-eslint/eslint-plugin-react/assets/93956840/55ca8aec-a488-4073-8677-88d2ccb7f0c6)
Clicking the first option sorts the props alphabetically 
![image](https://github.com/jsx-eslint/eslint-plugin-react/assets/93956840/db1f2814-9a1c-4cc1-9416-c198a6e6fd34)

When the faulty line is folowed with a comment
![image](https://github.com/jsx-eslint/eslint-plugin-react/assets/93956840/ef71f95d-5624-4eae-bc93-8161b8fb4967)
sorting doesn't work properly
![image](https://github.com/jsx-eslint/eslint-plugin-react/assets/93956840/54a78032-3ad9-4444-8b4b-1e463d9284f2)

### Expected Behavior

Comments in props should be ignored and sorting should work as usual

### eslint-plugin-react version

^7.29.4

### eslint version

^8.13.0

### node version

v16.20.1

**Comment by ljharb** [comment]
Comments can't be ignored - because there's no way to know if the comment attaches to the line before it, or after it - so the autofix quite intentionally ignores those lines, and you're forced to fix them manually.
