### ISSUE TITLE
[Bug]: Failed to load plugin 'react': es-iterator-helpers tried to access call-bind

### ISSUE THREAD

**Issue by lewandom** [jsx-eslint/eslint-plugin-react#3616]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

After upgrading to eslint-plugin-react 7.33.2, the following error appears when using Yarn PnP / Next.js lint:

`- info Linting and checking validity of types .- error ESLint: Failed to load plugin 'react' declared in '.eslintrc.json » eslint-config-next/core-web-vitals » redacted/.yarn/__virtual__/eslint-config-next-virtual-3dd005a3fc/0/cache/eslint-config-next-npm-13.4.16-745205b385-c4b6849c4b.zip/node_modules/eslint-config-next/index.js': es-iterator-helpers tried to access call-bind, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.  Required package: call-bind Required by: es-iterator-helpers@npm:1.0.12 (via redacted/.yarn/cache/es-iterator-helpers-npm-1.0.12-35df79bd02-df1800a64b.zip/node_modules/es-iterator-helpers/Iterator.from/)  Require stack: - redacted/.yarn/cache/es-iterator-helpers-npm-1.0.12-35df79bd02-df1800a64b.zip/node_modules/es-iterator-helpers/Iterator.from/index.js - redacted/.yarn/__virtual__/eslint-plugin-react-virtual-df620cb600/0/cache/eslint-plugin-react-npm-7.33.2-08f77ebc15-b4c3d76390.zip/node_modules/eslint-plugin-react/lib/util/Components.js - redacted/.yarn/__virtual__/eslint-plugin-react-virtual-df620cb600/0/cache/eslint-plugin-react-npm-7.33.2-08f77ebc15-b4c3d76390.zip/node_modules/eslint-plugin-react/lib/rules/boolean-prop-naming.js - redacted/.yarn/__virtual__/eslint-plugin-react-virtual-df620cb600/0/cache/eslint-plugin-react-npm-7.33.2-08f77ebc15-b4c3d76390.zip/node_modules/eslint-plugin-react/lib/rules/index.js - redacted/.yarn/__virtual__/eslint-plugin-react-virtual-df620cb600/0/cache/eslint-plugin-react-npm-7.33.2-08f77ebc15-b4c3d76390.zip/node_modules/eslint-plugin-react/configs/all.js - redacted/.yarn/__virtual__/eslint-plugin-react-virtual-df620cb600/0/cache/eslint-plugin-react-npm-7.33.2-08f77ebc15-b4c3d76390.zip/node_modules/eslint-plugin-react/index.js - redacted/.yarn/cache/@eslint-eslintrc-npm-2.1.2-feb0771c9f-bc742a1e3b.zip/node_modules/@eslint/eslintrc/dist/eslintrc.cjs Referenced from: redacted/.yarn/__virtual__/eslint-config-next-virtual-3dd005a3fc/0/cache/eslint-config-next-npm-13.4.16-745205b385-c4b6849c4b.zip/node_modules/eslint-config-next/index.js`

### Expected Behavior

The missing dependencies should be automatically installed.

The related es-iterator-helpers issue is https://github.com/es-shims/iterator-helpers/issues/3. When it is resolved, need to upgrade es-iterator-helpers version in this project.

### eslint-plugin-react version

v7.33.2

### eslint version

v8.47.0

### node version

v16.20.0

**Comment by ljharb** [comment]
Fixed in es-iterator-helpers v1.0.13. This project depends on es-iterator-helpers with a `^`, so no upgrade or change or release is needed here.

Note this works fine in actual npm, it just seems that PnP can't handle it.

**Comment by lewandom** [comment]
Verified, works well. Thanks for a quick resolution!
