### ISSUE TITLE
[Bug]: Performance Regression

### ISSUE THREAD

**Issue by jleider** [jsx-eslint/eslint-plugin-react#3619]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

Upgrading from 7.33.1 to 7.33.2 causes a few rules to slow down significantly. 

A few rules that appear to have gotten significantly slower are:

* `react/no-array-index-key` 
* `react/no-unstable-nested-components`
* `react/no-danger-with-children`

Our overall linting time goes from ~60s to ~90s only changing this one package.

Using eslint timing settings you can see here that these two rules are occupying a good amount of time relative to before the upgrade.

7.33.2:
```
react/no-array-index-key              | 21522.183 |    30.7%
react/no-unstable-nested-components   |  7283.991 |    10.4%
react/no-danger-with-children         |  2138.971 |     3.0%
```

7.33.1:
```
react/no-array-index-key              |   718.943 |     1.8%
react/no-unstable-nested-components   |  1208.373 |     3.0%
react/no-danger-with-children         |  Not slow enough to be in top 10
```

Pertinent package versions:

* eslint: 8.46.0 & 8.47.0
* eslint-plugin-react: 7.33.2
* @typescript-eslint/eslint-plugin: 6.2.1 & 6.4.1
* @typescript-eslint/parser: 6.2.1 & 6.4.1
* Node.js: 18.16.1
* Mac OS 13.5 - M1 MBP

Unfortunately I can't share our codebase and I don't have a reproduction. Hopefully the code diff between .1 and .2 are small enough to be able to track down this regression.

### Expected Behavior

I expect the two versions to be similar in speed. 

### eslint-plugin-react version

7.33.2

### eslint version

8.47.0

### node version

18.16.1

**Comment by ljharb** [comment]
Can you try checking out specific commits of this plugin and comparing? Specifically, how does 37b02ac2 perform?

**Comment by jleider** [comment]
After some further investigation of the plugin codebase, I see that there are a number of other shims in use. I wonder if those contribute to additional slowdowns? It would be interesting to see if replacing those with their native counterparts would speed things up more.

**Comment by ljharb** [comment]
For all of those, we support node versions that lack them, so replacing them isn’t likely an option.

Certainly some of the recent changes with es-iterator-helpers could be adjusted or reverted, though. My preference would be to keep as much of the changes as we can while avoiding the bulk of the perf penalty.

**Comment by ljharb** [comment]
@jleider could you check out *only* lib/util/Components.js prior to the es-iterator-helpers change, and have the rest be latest master, and let me know how the perf is?

**Comment by jleider** [comment]
I'm a little confused as to whats going on. I installed the latest master and replaced `lib/util/Components.js` in my local `node_modules` to [this version](https://github.com/jsx-eslint/eslint-plugin-react/blob/f17395e22c26d4385d0d800ed2ba4269941e49f0/lib/util/Components.js) and I'm still seeing the slowness.

**Comment by ljharb** [comment]
These are the three shared files that were modified in that commit:
```
lib/util/Components.js
lib/util/linkComponents.js
lib/util/propWrapper.js
```

If it's not too much to ask, revert just one of them at a time, and we can find which one is excessively slow?

**Comment by jleider** [comment]
I had the same thought. I rolled each file back to its previous version one by one and I didn't see any real changes. I rolled them all back and still no real change. I'm very confused. I even console logged to see if I was modifying the correct files and sure enough the logs were printed to the console. If I go and reinstall 7.33.1 everything is back to normal.

**Comment by ljharb** [comment]
oof, that doesn't make any sense. maybe eslint's doing some caching?

**Comment by ljharb** [comment]
This has been filed on v8 as https://bugs.chromium.org/p/chromium/issues/detail?id=1477372.

**Comment by ljharb** [comment]
Give `iterator.prototype` v1.1.1 a try.

**Comment by jleider** [comment]
Using 7.33.2 and iterator.prototype 1.1.1 it helps a little. Down from ~89s to ~78-80s but still not back down to the ~55-59s range as 7.33.1. 

```
Rule                                  | Time (ms) | Relative
:-------------------------------------|----------:|--------:
react/no-array-index-key              | 17831.444 |    28.9%
redos/no-vulnerable                   | 11373.265 |    18.4%
@typescript-eslint/no-unsafe-argument | 11122.301 |    18.0%
react/no-unstable-nested-components   |  6134.390 |     9.9%
import/no-duplicates                  |  5302.239 |     8.6%
react/no-danger-with-children         |  1932.733 |     3.1%
@typescript-eslint/no-redeclare       |   849.440 |     1.4%
@typescript-eslint/no-unused-vars     |   689.812 |     1.1%
camelcase                             |   562.923 |     0.9%
simple-import-sort/imports            |   428.665 |     0.7%

________________________________________________________
Executed in   80.72 secs    fish           external
   usr time   98.35 secs   33.00 micros   98.35 secs
   sys time    6.36 secs  356.00 micros    6.36 secs
```

**Comment by jleider** [comment]
Actually, rolling `iterator.prototype` back and forth between `1.1.0` and `1.1.1` yields the same results. My machine is just running the linter a bit faster today and I am not sure why. Perhaps no video conference or vscode live share stealing resources from the linter. Nothing else has changed.

**Comment by ljharb** [comment]
Snap, ok - presumably removing any requires of es-iterator-helpers fixes the issue, and adding a require iterator.prototype doesn’t re-cause it?

**Comment by jleider** [comment]
Starting with `7.33.1`

* importing `const i = require("iterator.prototype");` in Components.js exhibits no change in run time. 
* importing `const map = require('es-iterator-helpers/Iterator.prototype.map');` in Components.js causes the slowdown.
 
In each case, I only imported, the import was never referenced.

**Comment by ljharb** [comment]
Thanks, I'll keep looking for more root causes.

**Comment by ljharb** [comment]
Another potential candidate has appeared - is there any chance that updating to safe-array-concat v1.0.1 addresses the problem with `eslint-plugin-react` and `iterator.prototype` latest? (ref https://github.com/ljharb/safe-array-concat/pull/3)

**Comment by jleider** [comment]
@ljharb the update in https://github.com/ljharb/safe-array-concat/issues/2 fixes the issue. 

The change to `iterator.prototype` either has very little effect but is probably a good change anyway.

**Comment by ljharb** [comment]
Awesome :-) I’ll close this then. Thanks for helping me debug!
