### ISSUE TITLE
[Bug]: no-unknown-property gives false-positives on data-* attributes, but React gives warnings on them

### ISSUE THREAD

**Issue by HermanBilous** [jsx-eslint/eslint-plugin-react#3643]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

There was an https://github.com/jsx-eslint/eslint-plugin-react/issues/3395 issue raised, which resulted in the rule being updated to support passing data-* attributes with any casing, but even the sandbox the reporter provided included a warning from react: "Warning: React does not recognize the `data-testID` prop on a DOM element.". This is still an issue right now with react 18, as seen in this sandbox.

https://codesandbox.io/s/adoring-robinson-2z75gh

### Expected Behavior

Expected behaviour: data-* attributes are reported, when they have any capital letters. 

Actual behaviour: data-* attributes with uppercase letters are not reported by rule, react dumps warnings into console.

### eslint-plugin-react version

v7.33.2

### eslint version

v8.51.0

### node version

v20

**Comment by ljharb** [comment]
OK, so to clarify, even though browsers allow almost anything after `data-`, react only allows lowercased data attributes?

Changing the sandbox to a few other react versions indicates this warning exists in at least React 16+ (changing it to v15 or lower got annoying, so i gave up).

We'll need to add this as a new option to warn on.
