### ISSUE TITLE
[Bug]: No way to handle type discrimination with `react/destructuring-assignment`

### ISSUE THREAD

**Issue by 0-CAT** [jsx-eslint/eslint-plugin-react#3658]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

#### Description

When you accept a props type that is a union of two interfaces which can be discriminated, it is not possible to destructure the items which do not exist on one or more of the interfaces. However, `react/destructuring-assignment` does not recognize that, and so it fires when attempting to access the value from the props.

#### Example w/ error

```ts
interface P1 {
	a: true;
	b: number;
}

interface P2 {
	a: false;
}

type P = P1 | P2;

export const MyComponent: React.VFC<P> = (props) => {
	const { a } = props;

	const b = a ? props.b : undefined;

	return <span>{b}</span>;
};
```

![image](https://github.com/jsx-eslint/eslint-plugin-react/assets/104591838/8ab2a3b4-ab30-4bed-b54c-31f4d3ab925b)

This can't really be worked around if you need `b` to exist at the top level of the component (e.g., as an input or dependency for a `use*` call). I think the only real way to work around this is something like:

```ts
let b: P1["b"] | undefined;

if (a) {
	const { b: bTemp } = props;
	b = bTemp;
}
```

But this gets super, super cumbersome when you have more than one prop to handle this way.

### Expected Behavior

**Ideally:** The rule should be able to detect if the property does not exist on the union-ed props type, and in such a case should not fire.

**Alternatively:** There should be an optional setting to have this rule ignore ternary assignments for this specific use case.

### eslint-plugin-react version

v7.32.2

### eslint version

v8.44.0

### node version

v16.20.1

**Comment by ljharb** [comment]
It’s quite possible; if typescript doesn’t let you do it, typescript is broken.

**Comment by 0-CAT** [comment]
@ljharb I'm not sure what you mean. This is by design in TypeScript. In the example above, you cannot destructure `b` out of `props` because it is not guaranteed to exist on the type unless `a === true`. At destructure time, TS cannot tell if the object is `P1` or `P2`, you cannot pull out a field that is exclusive to `P1`.

![image](https://github.com/jsx-eslint/eslint-plugin-react/assets/104591838/c3344130-ba2c-4cfb-b080-b7e2c76cfcb7)

If necessary, I can find where this is documented in TS, but I can guarantee you it is by design.

**Comment by ljharb** [comment]
It’s JavaScript - every property is always guaranteed to yield undefined when absent. I understand how TS is designed, but the correct thing to do here is unconditionally destructure both properties. TS’s build-time fiction doesn’t change that,\.

**Comment by 0-CAT** [comment]
@ljharb So is the implication here that the linting supported by this library is not intended to be compatible with TypeScript?

**Comment by ljharb** [comment]
Of course it is; but if you happen to have selected a type that typescript doesn't support combined with react patterns, there’s not much we can do about that.

The runtime code should do what the rule suggests, full stop. If TS is telling you to do something subpar, then either TS, or your types, are subpar.

You can always use `// @ts-ignore`.

**Comment by 0-CAT** [comment]
This looks to be a difference in opinion where my take is that TypeScript is doing the right thing and protecting the devs/runtime from potentially ending up with a type or value that is unexpected, while—correct me if I'm wrong—your take is that the linter's strict enforcement is favored over the type-checking provided by TypeScript.

The issue I see here is that when working in a code base with other people of differing experience levels, disabling linting rules (which is the approach I've been using to work around this bug/feature ask) might make code less consistent or readable, but disabling TS itself opens the possibility of other developers making mistakes that cause functional runtime issues.

I guess if that's not a concern, then this issue isn't going to see any traction. However, given how many existing ESLint rules—even ones in this repository—have customization that leave it up to the maintainers of a given code base to decide how they want their code to be linted (i.e., tweak the behavior of "what the rule suggests"), I'm not really seeing the reason that such a customization could not exist for this rule.

**Comment by ljharb** [comment]
If `a` is absent, `undefined` is expected, so yes, I think that TS isn't doing the right thing here.

There are many customizations offered, but infinitely more that are not offered intentionally - just because someone wants something doesn't make it "not harmful" to have that thing, and lots of people want lots of things that would end up being harmful.

As to this specific request, if you need `b` at the top level of the component, then `b` isn't actually a property that *can* be absent from props, so your types are wrong. The type for the component shouldn't be `P1 | P2`, it should be `P1 | (P2 & { b?: never })` or something like that (i'd have to play with it in a TS context to be sure).

This problem is annoying also because TypeScript fails to differentiate between a component's external props types, and internal props types - externally, `P1 | P2` seems perfectly correct, but internally that's not the correct type for your implementation since you need `b` *in every code branch*.

**Comment by 0-CAT** [comment]
For this specific case, this comment actually helped me realize something:

> ... if you need `b` at the top level of the component, then `b` isn't actually a property that can be absent from props, so your types are wrong.

It's definitely the case that `b` is required at the top level—but only in half of the use cases of the component, which, thinking about it, is probably a React anti-pattern.

I'm thinking now that it's probably better to be explicit about this, where it's actually two separate components such that one takes `props: P1` and one takes `props: P2`—and still allow for logic common to both components to be exercised on `props: P`. (Example at the bottom of my comment.) It's a little difficult to illustrate in the contrived minimal example, but hopefully if anyone comes across this dilemma in the future, this is enough to show how I think I'll end up handling this (rather than `eslint-ignore`).

Appreciate the open discussion on this. Cheers.

---

```ts
interface P1 {
	a: true;
	b: number;
}

interface P2 {
	a: false;
}

type P = P1 | P2;

export const MyComponent: React.VFC<P> = (props) => {
	const { a } = props;

	// If needed, any common logic between the two forked components can go here, and be
	// passed in as props on the line below.

	return a ? <MyComponentWithATrue {...props} /> : <MyComponentWithAFalse {...props} />;
};

export const MyComponentWithATrue: React.VFC<P1> = (props) => {
	const { b } = props;

	return <span>{b}</span>;
};

export const MyComponentWithAFalse: React.VFC<P2> = (props) => {
	return <span>{/* ... */}</span>;
};
```

**Comment by ljharb** [comment]
Splitting it into two components definitely sounds like the best approach here.

I remain open to discussing a change in the rule to allow for exceptions, but to be compelling, I'd need a use case that isn't obviated by finding a better architecture :-)
