### ISSUE TITLE
[Bug]: Consider dropping the es-iterator-helpers dependency

### ISSUE THREAD

**Issue by TomiBelan** [jsx-eslint/eslint-plugin-react#3661]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

Now, I know this is a [weird use case](https://xkcd.com/1172/) and [not something promised in your public contract](https://www.hyrumslaw.com/), but hear me out:

Would you please consider reverting commit e1dd37f743649bf43726fe102a16bc71062d8687 and removing your dependency on es-iterator-helpers?

Since commit e1dd37f743649bf43726fe102a16bc71062d8687 has more added lines than deleted lines, I feel its value as a refactoring is fairly neutral at best.

**My weird use case:**

I'm a curmudgeon who cares too much about node_modules directory size.

It caught my attention that the total size of eslint-plugin-react is *as big as eslint itself*:

```shellsession
In an empty project:
$ npm install eslint
added 99 packages in 5s
$ du -sh node_modules/
15M     node_modules/
$ npm install eslint-plugin-react
added 93 packages, and audited 193 packages in 3s
$ du -sh node_modules/
31M     node_modules/
```

I looked into it and discovered that it's because eslint-plugin-react uses many polyfills to support ancient Node.js versions. Not something I need, but I can understand and respect it. 👍

Still, I had too much time and not enough common sense, so I used the npm "overrides" / yarn "resolutions" feature to override those libraries in my project. E.g. I replaced the `string.prototype.matchall` package with a one line file `module.exports = (string, pattern) => string.matchAll(pattern);`, and so on. This brought the total node_modules size of eslint-plugin-react down to 2MB - a much more reasonable number.

I am fully aware this is a silly thing to optimize. I'm not running out of hard disk space. It's about the principle. ;)
A world in which my project does not depend on libraries like `is-string` makes me happier than a world in which it does. ;)

In v7.33.2 this is not so easy to do. The other polyfills were only needed for old Node versions, but Iterator Helpers are still just a Stage 3 proposal and not yet implemented natively in any Node.js version. So it's not as easy for me to hack them out.

Thanks for reading and thanks for your work.
❤️ 

### Expected Behavior

&nbsp;

### eslint-plugin-react version

v7.33.2

### eslint version

v8.54.0

### node version

v21.2.0

**Comment by ljharb** [comment]
I appreciate your candor and awareness that it’s a silly thing to optimize.

The value of refactors has nothing to do with line count, which is a metric the entire industry learned decades ago was harmful to optimize for.

**Comment by TomiBelan** [comment]
Oh well. Thanks for replying!

**Comment by TomiBelan** [comment]
You are correct. is-string was not the best example.

is-string has a much better reason to exist than [left-pad](https://qz.com/646467/how-one-programmer-broke-the-internet-by-deleting-a-tiny-piece-of-code), [is-even](https://news.ycombinator.com/item?id=29241943), or [is-windows](https://old.reddit.com/r/programming/comments/c0zwxb/one_liner_npm_package_iswindows_has_25_million/). But it evokes similar feelings in me. I prefer [Russ Cox's](https://research.swtch.com/deps) view on dependencies. I hope that makes sense.

I guess what bothers me is that I don't really see the *upside* of commit e1dd37f743649bf43726fe102a16bc71062d8687. I don't find it more readable.

But it's up to your taste and your choice. Thanks for your work (even parts I disagree with). ❤️
