### ISSUE TITLE
[Bug]: `jsx-no-leaked-render` report `&&` in prop

### ISSUE THREAD

**Issue by AhmedBaset** [jsx-eslint/eslint-plugin-react#3719]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

Imagine you have a prop (e.g. `isOpen`), you want to set the value as `firstCondition === true && anotherCondition === true`. Currently the plugin report wrongly this kind of code which should be valid.

<img width="575" alt="image" src="https://github.com/jsx-eslint/eslint-plugin-react/assets/82659015/80d90a3d-2a08-428f-9fab-53617de3dc72">

### Expected Behavior

I expect to not throw

### eslint-plugin-react version

7.34.1

### eslint version

8.57.0

### node version

18

**Comment by ljharb** [comment]
i agree, this should be valid (altho `!!firstCondition && !!anotherCondition` would be more idiomatic)

**Comment by ljharb** [comment]
@A7med3bdulBaset specifically because a `0` is falsy but will render a literal zero - that's the point of the rule, and indeed is why `&&` conditional rendering is dangerous.

**Comment by A7med3bdulBaset** [comment]
I understand well `&&` and its cons/pros. 

I know `0 && content` will render `0`. My point is why `boolean && content`, `contentOrNullOrUndefinedOrBoolean && content` is prevented?

**Comment by ljharb** [comment]
I agree that neither of those should be prevented when the type is known.

**Comment by AhmedBaset** [comment]
Thanks @akulsr0 for working on this

**Comment by AhmedBaset** [comment]
`<Comp prop={cond1 && cond2} />` was solved. But, `dataOrUndefined && data...` still an issue. IMO the rule should only complain if the left side is of type number.

**Comment by ljharb** [comment]
More specifically, it should only complain if the left side is a *known type* and is not a number.

This should also be an option, I'd think, because TS isn't actually "type safety" and folks may not want to rely on it.

**Comment by ljharb** [comment]
Yes.

**Comment by AhmedBaset** [comment]
> Yes.

Done in #3754
