### ISSUE TITLE
`jsx-handler-names` support skipping prop naming checks

### ISSUE THREAD

**Issue by Max10240** [jsx-eslint/eslint-plugin-react#3722]
My project has many components from other dependency packages, like:
```tsx
<ComponentFromOtherLibraryFoo customPropNameFoo={handleSomething} />;
<ComponentFromOtherLibraryBar customPropNameBar={handleSomething} />;
```
Every time I come across them, I need to add an extra line of boring comments:
```tsx
// eslint-disable-next-line jsx-handler-names
<ComponentFromOtherLibraryFoo customPropNameFoo={handleSomething} />;
// eslint-disable-next-line jsx-handler-names
<ComponentFromOtherLibraryBar customPropNameBar={handleSomething} />;
```

To be honest, I don't care about the names of these PROPS(even the components in my own project, I just want it to check my handler function's name)

To make matters worse, if the prop's name is not camelCase (e.g., all lowercase letters: "foofoo"), the option "eventHandlerPropPrefix" is not valid either, because it only applies to CamelCase naming:
```tsx
/* with config: 
{
  eventHandlerPrefix: '(on|handle)',
  eventHandlerPropPrefix: '(on|foo)',
}
*/
// fine
<ComponentFromOtherLibraryFoo fooPropName={handleSomething} />;

// not work, still has error
<ComponentFromOtherLibraryFoo foo={handleSomething} />;
```
So, it would be nice if there were an option like "checkPropName". For those who don't care about prop naming, simply turn it off.
like:
```tsx
{
  eventHandlerPrefix: '(on|handle)',
  eventHandlerPropPrefix: '(on|foo)',
  // ...
  checkPropName: false,
}
```

Anyway, I want to confirm if this option is necessary (and if anyone else has experienced this), and if so, I can create a PR to do it.

**Comment by ljharb** [comment]
The rule's entire purpose is to check prop names.

I think it'd be reasonable to add an option with a list of component names to ignore, though.

**Comment by Max10240** [comment]
> I think it'd be reasonable to add an option with a list of component names to ignore, though.

Okay, let me try to implement it!

**Comment by akulsr0** [comment]
Since this was inactive for sometime now, I will raise a PR!
