### ISSUE TITLE
[Suggestion]: Drop support for node <16.20

### ISSUE THREAD

**Issue by SimonSchick** [jsx-eslint/eslint-plugin-react#3723]
I noticed this library still supports node v4, I'd suggest dropping support for anything <16.20 moving forward as this will allow removal of some polyfill libraries including:

<img width="293" alt="image" src="https://github.com/jsx-eslint/eslint-plugin-react/assets/3259089/8127236b-47f8-4766-9d89-e7f7bc8025c3">

**Comment by ljharb** [comment]
Thanks for the suggestion.
