### ISSUE TITLE
Quick question: does `settings.version` default to "detect" yet?

### ISSUE THREAD

**Issue by JstnMcBrd** [jsx-eslint/eslint-plugin-react#3758]
In the [README](https://github.com/jsx-eslint/eslint-plugin-react?tab=readme-ov-file#configuration-legacy-eslintrc-), it says that sometime in the future, `version` will default to `detect` instead of `latest`.

```js
{
  "settings": {
    "react": {
      // ...
      "version": "detect", // React version. "detect" automatically picks the version you have installed.
                           // You can also use `16.0`, `16.3`, etc, if you want to override the detected value.
                           // It will default to "latest" and warn if missing, and to "detect" in the future
      // ...
    },
    // ...
}
```

That would be a very useful change! But I don't know how long ago this part of the README was written. Have you already made this update? If not, are you still planning on it?

**Comment by ljharb** [comment]
Nope, if the change was made the readme would be updated.

This change can’t happen until a semver-major, and i almost never do those. Also, the recommended way to use this plugin is via the Airbnb config which already sets it to detect.

**Comment by JstnMcBrd** [comment]
I can't find anything in the readme about an airbnb config. Where is it recommended?

**Comment by ljharb** [comment]
It's not written in the readme, that's true :-) but i recommend it.
