### ISSUE TITLE
[Bug]: `non-jsx` is listed in `react/jsx-one-expression-per-line` options but is not available

### ISSUE THREAD

**Issue by mirabtellegen** [jsx-eslint/eslint-plugin-react#3773]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

In [these docs](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-one-expression-per-line.md) for  the `eslint` rule `react/jsx-one-expression-per-line`, a `non-jsx` `allow` option is mentioned that seems unavailable. 

<img width="560" alt="eslint rule docs" src="https://github.com/jsx-eslint/eslint-plugin-react/assets/145612743/3182665a-9fb3-4e7a-9655-40d39b4529f4">

### Expected Behavior

I would love for this option to become available, but it should otherwise be removed from the docs

### eslint-plugin-react version

v7.31.11

### eslint version

v8.28.0

### node version

v8.19.2

**Comment by ljharb** [comment]
That feature was released in v7.34.0. You're on v7.31.11. If you update to the latest you should be fine.
