### ISSUE TITLE
[Bug]: `sort-prop-types`'s autofix doesn't move the semicolon, producing broken code, on single-line Props types

### ISSUE THREAD

**Issue by tylerlaprade** [jsx-eslint/eslint-plugin-react#3783]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

`sort-prop-types`, with `checkTypes: true`, breaks the code when run on single-line Props with autofix due to the semicolon staying at the end instead of moving.

<img width="1773" alt="image" src="https://github.com/user-attachments/assets/ce3e6c5c-3615-48f4-bace-3b86f8453da3">

The props were rearranged without the semicolon dividing them

`eslint --fix`

### Expected Behavior

Semicolon be moved along with the moved prop when running autofix

```tsx
type CustomProps = { onChange: (event: { target: { name: string; value: string } }) => void; name: string };
```

should become

```tsx
type CustomProps = { name: string; onChange: (event: { target: { name: string; value: string } }) => void };
```

Instead, it is fixing to

```tsx
type CustomProps = { name: string onChange: (event: { target: { name: string; value: string } }) => void; };
```

### eslint-plugin-react version

v7.34.4

### eslint version

v8.57.0

### node version

v20.14.10

**Comment by tylerlaprade** [comment]
UPDATE: I found another case which produces an incorrect autofix, this one on a multi-line Props. It seems to be due to comments. Notice that the comments have been duplicated, three props have disappeared, and part of a typehint is on a line by itself.

#### Starting code:
```tsx
type Props = {
  onClose: () => void;
  onSave?: () => void;
  initialContractInfo?: ContractInfo; // used to pre-populate the form just for our tests
  contractVersionTraceId?: TraceId; // used when editing an existing contract
  contractContainerId: TraceId;
  wizardStartIndex?: number;
  contractStatus?: BackendContractStatus;
  contractVersion?: BackendContractVersion;
};
```

#### Auto-fixed code:
```tsx
type Props = {
  initialContractInfo?: ContractInfo; // used to pre-populate the form just for our tests
  // used to pre-populate the form just for our tests
  contractVersionTraceId?: TraceId; // used when editing an existing contract
  // used when editing an existing contract
  contractContainerId: TraceId;
  dContractVersion;
  onClose: () => void;
  onSave?: () => void;
};
```

#### Expected result:
```tsx
type Props = {
  initialContractInfo?: ContractInfo; // used to pre-populate the form just for our tests
  contractVersionTraceId?: TraceId; // used when editing an existing contract
  contractContainerId: TraceId;
  wizardStartIndex?: number;
  contractStatus?: BackendContractStatus;
  contractVersion?: BackendContractVersion;
  onClose: () => void;
  onSave?: () => void;
};
```

**Comment by ljharb** [comment]
@tylerlaprade can you provide the component code these are associated with? it won't repro without a component.

**Comment by ljharb** [comment]
Thanks, that definitely reproduces.

I'm not sure how to fix it, tbh, but i can certainly disable the autofix for types.

**Comment by tylerlaprade** [comment]
The autofix has been quite helpful in other cases. I imagine this would just be an issue of including the semicolon and/or comment in the moved token.

**Comment by ljharb** [comment]
right - it's not super clear to me how to DO that tho :-/

cc @akulsr0 from #3615, maybe you have an idea?

**Comment by tylerlaprade** [comment]
@ljharb, the description of #3784 says it only partially fixes this issue. Should we leave it open for the other half of the issue?

**Comment by akulsr0** [comment]
I feel the second one can be a seperate issue, for better tracking.

**Comment by ljharb** [comment]
Yeah it'd be very helpful to file a separate issue for that. Thanks!
