### ISSUE TITLE
[Bug]: Cannot ban only explicitSpread for jsx-props-no-spreading

### ISSUE THREAD

**Issue by divmgl** [jsx-eslint/eslint-plugin-react#3799]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

This rule:

    "react/jsx-props-no-spreading": [
      "error",
      {
        html: "ignore",
        custom: "ignore",
        explicitSpread: "enforce",
      },
    ],
    
Results in this crash:

```
ESLint: 8.57.0

Error: .eslintrc.cjs:
        Configuration for rule "react/jsx-props-no-spreading" is invalid:
        Value {"html":"ignore","custom":"ignore","explicitSpread":"enforce"} should NOT be valid.
```

Reproduction:

https://stackblitz.com/edit/vitejs-vite-dyngku?file=eslint.config.js

Run `pnpm lint`.

### Expected Behavior

Does not crash.

### eslint-plugin-react version

^7.35.0

### eslint version

^9.8.0

### node version

v18.20.3

**Comment by ljharb** [comment]
Looks like the schema wasn't changed in #2449, but I can't believe that zero people have tried to use the option in the last 5 years. cc @pawelnvk

**Comment by ljharb** [comment]
ah, maybe this is a new warning in eslint 9, and that's why nobody noticed.

**Comment by divmgl** [comment]
Hey guys, this is not a warning. This is a crash. I cannot set this on the latest version of ESLint and `eslint-plugin-react`.

**Comment by divmgl** [comment]
We specifically want to avoid:

```tsx
<SomeComponent
  {...{ 
    onClick,
    onSubmit,
    render: <SomeOtherComponent />
  }}
/>
```
