### ISSUE TITLE
[Bug]: Support ESLint v9.9.0

### ISSUE THREAD

**Issue by Byron2016** [jsx-eslint/eslint-plugin-react#3800]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

It is related to [plugins currently do not support ESLint v9 yet. ](https://github.com/eslint/eslint/issues/18766)

```
pnpm create @eslint/config@latest
```

```
√ How would you like to use ESLint? · problems
√ What type of modules does your project use? · esm
√ Which framework does your project use? · react
√ Does your project use TypeScript? · typescript
√ Where does your code run? · browser
The config that you've selected requires the following dependencies: eslint@9.x, globals, @eslint/js, typescript-eslint, eslint-plugin-react
√ Would you like to install them now? · No / Yes
√ Which package manager do you want to use? · pnpm
```

```
+ eslint-plugin-react 7.35.0

**Note that some plugins currently do not support ESLint v9 yet.
You may need to use '--force' when installing**
```

### Expected Behavior

I would like to know if currenty **eslint-plugin-react** works fine with eslint V9.9.0

### eslint-plugin-react version

v7.35.0

### eslint version

v9.9.0

### node version

v20.15.1

**Comment by ljharb** [comment]
yes, the peer deps explicitly say that it supports eslint `^9.7`. The warning isn't specific to this plugin, it's from that eslint/config package.
