### ISSUE TITLE
Rule proposal: Auto fix `prop={prop}` to `{...{prop}}`

### ISSUE THREAD

**Issue by nikitarevenco** [jsx-eslint/eslint-plugin-react#3804]
Some people may prefer not duplicating the property name. For example instead of:
```tsx
<MDXRemote source={source} />
```

We can write:
```tsx
<MDXRemote {...{ source }} />
```

Would it be possible to have a rule for this, as well as auto-fixer? The rule can also take a setting `number`, which will dictate the minimum number of repeated properties that we need in order for the rule to trigger.

For example with this configuration:

```json
"react/new-rule-name": ["error", {  minimum: 2 }
```

The following won't error:

```tsx
<Component prop1={prop1} />
```

But this will:

```tsx
<Component prop1={prop1} prop2={prop2} />
```

and get auto-fixed to:

```tsx
<Component {...{prop1, prop2}} />
```

**Comment by ljharb** [comment]
I suppose we could, but that creates a performance hit and is a pretty long-discouraged practice, as I understand it.

**Comment by nikitarevenco** [comment]
> I suppose we could, but that creates a performance hit and is a pretty long-discouraged practice, as I understand it.

Is the performance hit non-negligible? I've found the approach from people encouraging it when someone complains that react doesn't have `{prop}` syntax sugar

If there will be teams who'd prefer to have this option rather than not, wouldn't that already make a good justification for adding it? Just don't turn it on by default

**Comment by ljharb** [comment]
I'm not sure whether it's negligible, but picking a messier and inherently slower approach - even if negligibly - doesn't seem like a good choice merely for an aesthetic preference. Adding the option implies that it's a non-harmful choice.

**Comment by nikitarevenco** [comment]
> I'm not sure whether it's negligible, but picking a messier and inherently slower approach - even if negligibly - doesn't seem like a good choice merely for an aesthetic preference. Adding the option implies that it's a non-harmful choice.

Ok, that's a good justification 👍
