### ISSUE TITLE
[Bug]: `jsx-curly-brace-presence` creating invalid code when auto-fixing

### ISSUE THREAD

**Issue by dennisoelkers** [jsx-eslint/eslint-plugin-react#3814]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

In version 7.35.1, #3798 is introducing a regression for us, it is changing:

```
help={'The maximum time range for searches. (i.e. "P30D" for 30 days, "PT24H" for 24 hours)'}
```
to
```
help="The maximum time range for searches. (i.e. "P30D" for 30 days, "PT24H" for 24 hours)"
```

which is obviously an incorrect string.

### Expected Behavior

It should not auto-fix this statement.

### eslint-plugin-react version

v7.35.1

### eslint version

v8.57.0

### node version

v18.20.4

**Comment by ljharb** [comment]
k yeah, it just has to not autofix it, and you'll need to manually fix the straight quotes.

**Comment by ljharb** [comment]
I'll try to get a v7.35.2 out with this today.

**Comment by dennisoelkers** [comment]
Thanks for the quick fix and release, @ljharb!
