### ISSUE TITLE
[Bug]: indentation incorrect

### ISSUE THREAD

**Issue by zzzgit** [jsx-eslint/eslint-plugin-react#3815]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

<img width="693" alt="image" src="https://github.com/user-attachments/assets/19ac072d-9e22-45fa-8749-3e2935722b44">

It indents like this even though I have this rule enabled: 

`  react/jsx-indent-props: [2, 'tab']`

### Expected Behavior

indent as normal

### eslint-plugin-react version

7.35.2

### eslint version

8.57.0

### node version

20.11.0

**Comment by ljharb** [comment]
That rule only covers indentation of *props* for a multiline component. Do you also have `react/jsx-indent` enabled? (i'd strongly suggest using the airbnb config)

**Comment by zzzgit** [comment]
> react/jsx-indent

You resolved my problem.
