### ISSUE TITLE
[CI]: Unnecssary CI runs waste time & resources

### ISSUE THREAD

**Issue by StyleShit** [jsx-eslint/eslint-plugin-react#3832]
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

When working on a PR, I noticed that when I push a commit to my branch, it doesn't cancel the currently running workflows (and there are hundreds of them). It means that the github workers are busy and won't start the workflows for the newly committed changes until the previous ones finish.

It can be solved using workflow concurrency, and specifically [`cancel-in-progress: true`](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs#using-concurrency-in-different-scenarios)

Willing to open a PR for that if accepted 😄

**Comment by ljharb** [comment]
That's by design, because if they're auto-cancelled, you can't tell when they started to fail when pushing multiple commits.

**Comment by StyleShit** [comment]
oh, make sense actually

thanks for the quick response 😄
