### ISSUE TITLE
`no-unknown-property` doesn't prevent use of unknown properties?

### ISSUE THREAD

**Issue by ryb73** [jsx-eslint/eslint-plugin-react#757]
Today React gave me an ["unknown prop"](https://facebook.github.io/react/warnings/unknown-prop.html) warning:

![image](https://cloud.githubusercontent.com/assets/943476/17540030/c37499a6-5e78-11e6-83ba-9820d7a11874.png)
In this example, I gave my `div` element an `abc` attribute, which is obviously invalid HTML.

I was surprised that my linter didn't pick up on this. Looking at the documentation, the name and description of the `no-unknown-property` rule lead me to believe that this should be caught, but that doesn't appear to be the case.

So, I suppose this is a feature request: add a rule to catch invalid DOM properties.

**Comment by ljharb** [comment]
Were you using spread props, or was it an explicit prop directly on a DOM element?

**Comment by ryb73** [comment]
It was explicit.

**Comment by ljharb** [comment]
I definitely think `no-unknown-property` should be erroring out on all the same DOM element props that React 15.3 now does.

**Comment by mvirbicianskas** [comment]
was this fixed at some point? I can confirm it doesn't work as expected :/

**Comment by ljharb** [comment]
@mvirbicianskas no, but a PR would be welcome.

**Comment by sjarva** [comment]
Phew. This issue looked like "nice and small", but well, was more detective work than I expected 😅 

If anyone has more use cases than `<div abc="foo" />`, feel free to read through and comment on the PR #3377

**Comment by ryb73** [comment]
That's awesome, thanks @sjarva!
