### ISSUE TITLE
Rule proposal: disallow defaultValue and defaultChecked props to input

### ISSUE THREAD

**Issue by mlee** [jsx-eslint/eslint-plugin-react#990]
https://facebook.github.io/react/docs/uncontrolled-components.html

If you wanted to strictly enforce use of controlled components, you would never use defaultValue or defaultChecked. Although this rule would not by itself prevent the use of uncontrolled components, it would make it harder to create them.

**Comment by ljharb** [comment]
You can use `forbid-dom-props` to prevent ANY html element from using those props. Would that suffice?

**Comment by ljharb** [comment]
Closing, but can reopen if that doesn't cover the use case.
